import { scriptAssist, modelOptions, closeComposer } from './text-assistance-tools.js';
import { test, expect } from './fixtures.js';
import { cropImageInput, imageOutput, toolsTab, addImageReference } from './workspace-tools.js';

async function configure(page) {
  await page.goto('/settings/ai');
  const connections = page.getByRole('tab', { name: 'Connections', exact: true });
  await expect(async () => { await connections.click(); await expect(connections).toHaveAttribute('aria-selected', 'true'); }).toPass();
  const codex = page.getByRole('tab', { name: 'Codex', exact: true });
  await expect(async () => { await codex.click(); await expect(codex).toHaveAttribute('aria-selected', 'true'); }).toPass();
  await page.getByRole('checkbox', { name: 'Enable Codex', exact: true }).check();
  const card = page.locator('form').filter({ has: page.getByRole('heading', { name: 'Codex', exact: true }) });
  await card.getByRole('button', { name: 'Check connection', exact: true }).click();
  await expect(card).toContainText('qa@example.test');
  await card.getByRole('button', { name: 'Save Codex connection', exact: true }).click();
  await expect(page.locator('.settings-feedback')).toContainText('Codex connection saved');
  await expect(card).toContainText('85% remaining');
  await expect(card).toContainText('Supported by this CLI');
  await expect(card.locator('.codex-usage-window')).toHaveCount(1);
  await expect(card.locator('.codex-usage-window')).toContainText('5-hour');
  await expect(card.locator('.codex-usage')).not.toContainText('Unavailable');
  await page.getByRole('tab', { name: 'Text models', exact: true }).click();
  await expect(page.getByRole('tablist', { name: 'Text model providers' }).getByRole('tab', { name: 'Codex', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByText('Codex defaults', { exact: true }).click();
  await page.getByLabel('Default Codex reasoning effort', { exact: true }).selectOption('high');
  await page.getByRole('button', { name: 'Save default effort', exact: true }).click();
  await expect(page.locator('.settings-feedback')).toContainText('Default Codex reasoning effort saved');
  await page.getByRole('button', { name: 'Star Codex QA', exact: true }).click();
  await page.getByRole('tab', { name: 'Image models', exact: true }).click();
  const workflows = page.getByRole('tablist', { name: 'Image workflows' });
  await workflows.getByRole('tab', { name: 'Codex Images', exact: true }).click();
  await expect(page.getByLabel('Codex agent model', { exact: true })).toBeVisible();
  await expect(page.locator('#codex-image-model-help')).toContainText('Image model: managed by Codex');
  await page.getByRole('button', { name: 'Refresh Codex models', exact: true }).click();
  await page.locator('#codex-image-model').selectOption('mock-codex');
  await page.locator('#codex-image-effort').selectOption('high');
  await page.getByRole('button', { name: 'Save Codex Images', exact: true }).click();
  await expect(page.locator('.settings-feedback')).toContainText('Codex Images saved');
  // Saving a workflow does not make it the default; Defaults does.
  await workflows.getByRole('tab', { name: 'Defaults', exact: true }).click();
  await page.locator('#image-workflow').selectOption('CodexImages');
  await page.getByRole('button', { name: 'Save image defaults', exact: true }).click();
  await expect(page.locator('.settings-feedback')).toContainText('Image defaults saved');
}
async function asset(page, request) {
  const { id } = await (await request.get('/fixtures/new')).json();
  const library = await (await request.post(`/fixtures/${id}/images?patterned=true`)).json();
  await page.goto(`/projects/${id}/assets`); await toolsTab(page, 'Prompt');
  return { id, library };
}
test.afterEach(async ({ request }) => { await request.post('/fixtures/codex-reset'); });

test('script reasoning and response review look actionable on desktop and mobile', async ({ page, request }) => {
  await page.setViewportSize({ width: 1173, height: 1272 }); await configure(page);
  const { id } = await (await request.get('/fixtures/new')).json();
  await page.goto(`/projects/${id}/script`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await modelOptions(page, page.locator('.script-assistant'));
  await page.getByRole('combobox', { name: 'Text model', exact: true }).selectOption('Codex\nmock-codex\n');
  await page.getByText('Reasoning', { exact: true }).click();
  const effort = page.getByRole('combobox', { name: 'Reasoning effort', exact: true });
  await expect(effort).toHaveValue('');
  expect(await effort.evaluate(el => parseFloat(getComputedStyle(el).borderTopWidth))).toBeGreaterThan(0);
  expect((await effort.boundingBox()).height).toBeGreaterThanOrEqual(36);
  await effort.focus(); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Tab');
  await expect(effort).toHaveValue('low');
  await effort.selectOption('');
  await page.getByRole('button', { name: 'Set as project default', exact: true }).click();
  await scriptAssist(page);
  await page.locator('#script-operation').selectOption('Discuss');
  await page.locator('#script-instructions').fill('Suggest a reason for a surprise visitor.');
  await page.getByRole('button', { name: 'Discuss idea', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Review script proposal' });
  await expect(dialog.locator('.markdown-view')).toBeVisible();
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const review = page.getByRole('button', { name: /^(Review changes|View response|Needs attention)$/ });
  expect(await review.evaluate(el => parseFloat(getComputedStyle(el).borderTopWidth))).toBeGreaterThan(0);
  await page.screenshot({ path: 'test-results/codex-script-controls-desktop.png' });
  await review.focus(); await page.keyboard.press('Enter'); await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await modelOptions(page, page.locator('.script-assistant'));
  await page.getByText('Reasoning', { exact: true }).click();
  await expect(effort).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/codex-script-controls-mobile.png' });
});

test('Codex connection, text enhancement, reasoning choice, apply and image create', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 }); await configure(page);
  const { id } = await asset(page, request);
  await expect(page.locator('#asset-image-workflow')).toHaveValue('CodexImages');
  await page.locator('#image-prompt').fill('A watercolor mouse. Keep the sign ÖPPET.');
  await modelOptions(page, page.locator('.prompt-enhancement'));
  await page.getByRole('combobox', { name: 'Text model', exact: true }).selectOption('Codex\nmock-codex\n');
  await page.getByText('Reasoning', { exact: true }).click();
  await expect(page.getByLabel('Reasoning effort', { exact: true })).toHaveValue('');
  await expect(page.getByLabel('Reasoning effort', { exact: true })).toContainText('Use settings default · high');
  await page.getByLabel('Reasoning effort', { exact: true }).selectOption('low');
  await page.getByRole('button', { name: 'Set as project default', exact: true }).click();
  if (!await page.locator('.ai-assist-dialog').getByRole('button', { name: 'Enhance', exact: true }).isVisible()) await page.getByRole('button', { name: 'Improve prompt', exact: true }).click();
  await page.getByRole('button', { name: 'Enhance', exact: true }).click();
  const dialog = page.locator('.prompt-enhancement-dialog');
  await expect(dialog.getByRole('button', { name: 'Apply changes', exact: true })).toBeEnabled();
  await dialog.locator('#enhancement-suggestion').fill('A watercolor mouse beside the sign "ÖPPET".');
  await dialog.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(page.locator('#image-prompt')).toHaveValue('A watercolor mouse beside the sign "ÖPPET".');
  await page.getByRole('button', { name: 'Generate images', exact: true }).click();
  const review = page.locator('.image-review-dialog'); await expect(review).toBeVisible();
  await expect.poll(async () => (await (await request.get(`/fixtures/${id}`)).json()).assets.assets[0].images.length).toBe(2);
  const result = (await (await request.get(`/fixtures/${id}`)).json()).assets.assets[0].images.at(-1);
  expect(result.generation.codex.effort).toBe('high'); expect(result.width).toBe(80); expect(result.height).toBe(40);
  expect(result.generation.codex.timing.completedUtc).toBeTruthy();
  expect(result.generation.codex.timing.imageCalls).toHaveLength(1);
  await review.locator('summary').filter({ hasText: 'Metadata' }).click();
  await expect(review.locator('.codex-image-timing')).not.toHaveAttribute('open', '');
  await review.locator('.codex-image-timing > summary').click();
  await expect(review.locator('.codex-image-timing')).toContainText('Agent preparation');
  await expect(review.locator('.codex-image-timing')).toContainText('Image tool');
  await expect(review.locator('.codex-image-timing')).toContainText('Agent follow-up');
  await expect(review).toContainText('Not reported by Codex');
  await page.screenshot({ path: 'test-results/codex-image-timing-desktop.png' });
  await review.getByRole('button', { name: 'Close image review', exact: true }).click();
  await page.reload(); await toolsTab(page, 'Prompt');
  // Improve prompt needs a prompt before its model options can be opened.
  await page.locator('#image-prompt').fill('A watercolor mouse.');
  await modelOptions(page, page.locator('.prompt-enhancement'));
  await page.getByText('Reasoning', { exact: true }).click();
  await expect(page.getByLabel('Reasoning effort', { exact: true })).toHaveValue('low');
  await closeComposer(page);
  await toolsTab(page, 'Inputs'); await expect(page.locator('.lora-panel:visible')).toHaveCount(0);
  await imageOutput(page); await expect(page.locator('#fixed-seed')).toHaveCount(0);
});

test('Codex edit, independent crops, vision, comparison, more takes and mobile', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 }); await configure(page);
  const { id, library } = await asset(page, request);
  await page.locator('.asset-media-card[data-media-kind=Image] .media-select').click();
  await toolsTab(page, 'Inputs');
  await addImageReference(page, `${library.assets[1].id}/${library.assets[1].images[0].id}`);
  await cropImageInput(page,0,2); await cropImageInput(page,1,4);
  await toolsTab(page, 'Prompt'); await page.locator('#image-prompt').fill('Transfer the jacket from image 2 onto image 1.');
  await modelOptions(page, page.locator('.prompt-enhancement'));
  await page.getByRole('combobox', { name: 'Text model', exact: true }).selectOption('Codex\nmock-codex\n');
  await page.getByText('Reasoning', { exact: true }).click();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  if (!await page.locator('.ai-assist-dialog').getByRole('button', { name: 'Enhance', exact: true }).isVisible()) await page.getByRole('button', { name: 'Improve prompt', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Inspect reference images', exact: true }).check();
  await page.getByRole('button', { name: 'Enhance', exact: true }).click();
  const dialog = page.locator('.prompt-enhancement-dialog'); await expect(dialog.getByRole('button', { name: 'Apply changes', exact: true })).toBeEnabled();
  await dialog.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await page.getByRole('button', { name: 'Generate edited images', exact: true }).click();
  const review = page.locator('.image-review-dialog'); await expect(review).toBeVisible();
  await review.getByRole('button', { name: 'Compare with Source', exact: true }).click();
  await expect(review.locator('.review-wipe')).toBeVisible();
  await review.getByRole('button', { name: 'Generate more…', exact: true }).click();
  await page.getByRole('button', { name: 'Queue 1 image', exact: true }).click();
  await expect(review.getByRole('button', { name: 'View Take 2', exact: true })).toBeVisible();
  await review.getByRole('button', { name: 'Discard Take 1', exact: true }).click();
  await review.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(review.getByRole('button', { name: 'View Take 1', exact: true })).toBeVisible();
  await review.locator('summary').filter({ hasText: 'Metadata' }).click();
  await expect(review.locator('.codex-image-timing')).toBeVisible();
  const timing = review.locator('.codex-image-timing');
  await expect(timing).not.toHaveAttribute('open');
  await timing.locator('summary').click();
  await expect(timing).toHaveAttribute('open', '');
  const help = timing.getByRole('button', { name: 'Help: Codex image timing', exact: true });
  const note = timing.getByRole('note');
  await expect(note).not.toBeVisible();
  const timingHeight = await timing.evaluate(el => el.clientHeight);
  await help.focus(); await help.press('Enter');
  await expect(note).toContainText('Elapsed time within Codex, including waiting.');
  await expect(note).toBeVisible();
  expect(await timing.evaluate(el => el.clientHeight)).toBe(timingHeight);
  await page.keyboard.press('Escape');
  await expect(note).not.toBeVisible();
  await expect(help).toBeFocused();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/codex-mobile-review.png' });
  await review.locator('.codex-image-timing').scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'test-results/codex-image-timing-mobile.png' });
  const state = (await (await request.get(`/fixtures/${id}`)).json()).assets.assets[0].images;
  expect(state.at(-1).generation.edit.references).toHaveLength(2);
  expect(state.at(-1).generation.edit.sourceCrop).toBeTruthy();
  expect(state.at(-1).generation.edit.referenceCrops).toHaveLength(1);
});

test('A Codex usage-limit failure pauses the queue until an explicit resume and queued work survives navigation', async ({ page, request }) => {
  await configure(page); const { id } = await asset(page, request);
  // Codex reports the exhausted limit by failing the turn; nothing is blocked up front.
  await request.post('/fixtures/codex-quota?used=100');
  await page.locator('#image-prompt').fill('A small bird.');
  await page.getByRole('button', { name: 'Generate images', exact: true }).click();
  await page.locator('.ai-activity-trigger').click();
  const activity = page.getByRole('dialog', { name: 'AI activity', exact: true });
  await expect(activity.getByRole('button', { name: 'Resume queue Codex', exact: true })).toBeVisible();
  await activity.getByRole('button', { name: 'Close AI activity' }).click();
  // Generate cleared the composer, so the next request is written again.
  await page.locator('#image-prompt').fill('A small bird.');
  await page.getByRole('button', { name: 'Generate images', exact: true }).click();
  await expect(page.locator('.generation-panel .ai-queue-wait')).toBeVisible();
  await request.post('/fixtures/codex-quota?used=15');
  await page.goto('/'); await page.locator('.ai-activity-trigger').click();
  await activity.getByRole('button', { name: 'Resume queue Codex', exact: true }).click();
  await expect.poll(async () => (await (await request.get(`/fixtures/${id}`)).json()).assets.assets[0].images.length).toBe(2);
});


test('Activity places readable Codex allowance inside its collapsed provider row', async ({ page }) => {
  await configure(page);
  await page.locator('.ai-activity-trigger').click();
  const activity = page.getByRole('dialog', { name: 'AI activity', exact: true });
  await expect(activity.locator('.codex-usage')).toHaveCount(0);
  await activity.locator('.ai-provider-toggle').filter({ hasText: 'Codex' }).click();
  await expect(activity.locator('.codex-usage-window')).toContainText('85% remaining');
  await expect(activity.locator('.codex-usage-window')).toContainText('5-hour');
  await page.screenshot({ path: 'artifacts/validation/activity-codex-desktop.png' });
  await activity.locator('.ai-provider-toggle').filter({ hasText: 'Codex' }).click();
  await expect(activity.locator('.codex-usage')).toHaveCount(0);
});
