import { cropReference, openShotSetup } from './workspace-tools.js';
import { test, expect } from './fixtures.js';
const library = async (request, id) => (await (await request.get(`/fixtures/${id}`)).json()).assets;
async function tools(page) {
  const toggle = page.locator('[data-toggle-pane=right]');
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await expect(async () => { if (!await page.locator('.workspace-right').isVisible()) await toggle.click({ timeout: 1000 }); }).toPass({timeout:10000});
}
for (const narrow of [false, true]) test(`environment camera choices preserve writing and compose held views (${narrow ? 'narrow' : 'desktop'})`, async ({ page, request }) => {
  test.setTimeout(90000);
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`); await request.post(`/fixtures/${id}/environment-reel-owner`);
  const asset = (await library(request, id)).assets[0];
  await page.setViewportSize({ width: narrow ? 390 : 1173, height: narrow ? 844 : 1000 });
  await page.goto(`/projects/${id}/assets?assetId=${asset.id}&view=reels`); await tools(page);
  const editor = page.locator('.reel-tools');
  await expect(editor.locator('[data-prompt-ready]')).toHaveAttribute('data-prompt-ready', 'true');
  await editor.getByRole('textbox', { name: 'H3 prompt', exact: true }).fill('My authored camera prompt');
  await editor.getByLabel('Use guidance', { exact: true }).fill('My authored room guidance');
  await editor.getByRole('button', { name: 'Reel assistance', exact: true }).click();
  const assist = page.getByRole('dialog', { name: 'Reel assistance', exact: true });
  const presets = [
    ['EnvironmentHalfTurn', 'Half-turn reveal', 10, true], ['EnvironmentHeldViews', 'Held viewpoints', 15, true],
    ['EnvironmentPan', 'Short reveal', 6, true], ['EnvironmentPullBack', 'Pull back', 6, false],
    ['EnvironmentApproach', 'Move toward a feature', 6, false], ['EnvironmentArc', 'Arc around a feature', 6, true],
    ['EnvironmentPath', 'Custom path', 10, false], ['EnvironmentTurn', 'Full-room survey', 15, true]
  ];
  for (const [value, label, seconds, direction] of presets) {
    await assist.getByLabel('Camera preset', { exact: true }).selectOption({ label });
    await expect(assist.getByLabel('Camera duration (seconds)', { exact: true })).toHaveValue(String(seconds));
    await expect(assist.getByLabel('Camera direction', { exact: true })).toHaveCount(direction ? 1 : 0);
    await expect(assist.getByText(/Use keyframes to reference all angles/)).toHaveCount(seconds >= 10 ? 1 : 0);
    await expect.poll(async () => (await library(request, id)).reelDrafts[0].framing).toBe({ EnvironmentTurn:5, EnvironmentPan:6, EnvironmentPath:7, EnvironmentHalfTurn:8, EnvironmentHeldViews:9, EnvironmentPullBack:10, EnvironmentApproach:11, EnvironmentArc:12 }[value]);
    const draft = (await library(request, id)).reelDrafts[0];
    expect(draft.prompt).toBe('My authored camera prompt'); expect(draft.useGuidance).toBe('My authored room guidance');
  }
  await assist.getByLabel('Camera preset').selectOption('EnvironmentPan');
  await expect(assist.locator('.reel-camera-summary')).toContainText('opening objects leave the frame');
  await assist.getByText('Camera timing', { exact: true }).click();
  await expect(assist.locator('.reel-framing-plan')).toContainText('pans right with large amplitude at fast speed');
  await expect(assist.locator('.reel-framing-plan')).toContainText('leave through the left edge');
  await assist.getByLabel('Camera direction').selectOption('Left');
  await expect(assist.locator('.reel-framing-plan')).toContainText('leave through the right edge');
  await assist.getByLabel('Camera preset').selectOption('EnvironmentArc');
  await expect(assist.locator('.reel-camera-summary')).toContainText('broad 90° arc');
  await expect(assist.locator('.reel-framing-plan')).toContainText('distinct side-on viewpoint');
  await assist.getByText('Camera timing', { exact: true }).click();
  await assist.getByLabel('Camera preset').selectOption('EnvironmentTurn');
  await expect.poll(async () => (await library(request, id)).reelDrafts[0].framing).toBe(5);
  await expect(assist.getByLabel('Camera duration (seconds)')).toHaveValue('15');
  await assist.getByLabel('Camera direction').selectOption('Left');
  await assist.getByLabel('Camera duration (seconds)').fill('7');
  await assist.getByLabel('Instructions', { exact: true }).fill('Keep the brick wall and doorway fixed.');
  await expect(assist.getByText(/Suggested duration: 15 seconds/)).toBeVisible();
  await expect(assist.getByText(/Use keyframes to reference all angles/)).toHaveCount(0);
  await assist.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(editor.getByText(/Check prompts · Inputs/)).toBeVisible();
  expect((await (await request.get('/fixtures/reel-compositions')).json()).filter(c => c.context.environment?.assetId === asset.id)).toHaveLength(0);
  await page.reload(); await tools(page);
  await editor.getByRole('button', { name: 'Reel assistance', exact: true }).click();
  await expect(assist.getByLabel('Camera direction')).toHaveValue('Left');
  await expect(assist.getByLabel('Camera duration (seconds)')).toHaveValue('7');
  await expect(assist.getByLabel('Instructions', { exact: true })).toHaveValue('Keep the brick wall and doorway fixed.');
  await assist.getByLabel('Camera duration (seconds)').fill('16');
  await assist.getByLabel('Instructions', { exact: true }).focus();
  await expect(assist.getByText('Generated duration: Choose a supported duration')).toBeVisible();
  await assist.getByLabel('Camera duration (seconds)').fill('7');
  await assist.getByLabel('Instructions', { exact: true }).focus();
  await expect(assist.getByText('Generated duration: Choose a supported duration')).toHaveCount(0);
  await assist.getByLabel('Camera preset').selectOption('EnvironmentHeldViews');
  await assist.getByText('Camera timing', { exact: true }).click();
  await expect(assist.locator('.reel-framing-plan')).toContainText('[Shot 4]');
  await expect(assist.locator('.reel-framing-plan')).toContainText('left');
  await page.screenshot({ path: `artifacts/environment-presets-${narrow ? 'narrow' : 'desktop'}.png` });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await assist.getByRole('button', { name: 'Close', exact: true }).click();
  await editor.getByRole('textbox', { name: 'H3 prompt', exact: true }).fill('');
  await editor.getByLabel('Use guidance', { exact: true }).fill('');
  await editor.getByRole('button', { name: 'Manage reel references' }).click();
  const pictures = page.locator('.reel-pictures-dialog');
  await pictures.locator(`[data-reference="${asset.id}/${asset.images[0].id}"]`).click();
  await pictures.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await editor.getByRole('button', { name: 'Reel assistance', exact: true }).click();
  await assist.locator('.model-chip').click();
  await page.getByRole('combobox', { name: 'Text model', exact: true }).selectOption({ label: 'OpenRouter · Alternate mock model' });
  await page.getByRole('button', { name: 'Set as project default', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Text model', exact: true })).not.toBeVisible();
  const compose = assist.getByRole('button', { name: 'Compose pair', exact: true });
  await expect(compose).toBeEnabled(); await compose.focus(); await expect(compose).toBeInViewport(); await compose.press('Enter');
  await expect(assist).not.toBeVisible();
  await expect(editor.getByRole('textbox', { name: 'H3 prompt', exact: true })).toContainText('[Shot 4]', { timeout: 25000 });
  await expect(editor.getByRole('textbox', { name: 'H3 prompt', exact: true })).toContainText('screen positions change');
  const requests = (await (await request.get('/fixtures/reel-compositions')).json()).filter(c => c.context.environment?.assetId === asset.id);
  expect(requests).toHaveLength(1);
  expect(requests[0].context.presetViews).toContain('[Shot 4]'); expect(requests[0].context.presetViews).toContain('left');
  expect(requests[0].context.presetViews).toContain('four different directions');
});
for (const narrow of [false, true]) test(`environment reel composes, saves and supplies the setting to Shots (${narrow ? 'narrow' : 'desktop'})`, async ({ page, request }) => {
  test.setTimeout(150000);
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images?patterned=true`);
  await request.post(`/fixtures/${id}/environment-reel-owner`);
  const asset = (await library(request, id)).assets[0];
  await page.setViewportSize({ width: narrow ? 390 : 1173, height: narrow ? 844 : 1000 });
  await page.goto(`/projects/${id}/assets?assetId=${asset.id}&view=reels`);
  await expect(page.getByLabel('Filter media', { exact: true })).toHaveValue('Reels');
  await tools(page);
  const editor = page.locator('.reel-tools');
  await expect(editor.locator('[data-prompt-ready]')).toHaveAttribute('data-prompt-ready', 'true');
  await expect(editor.getByRole('combobox', { name: 'Aspect', exact: true })).toHaveValue('16:9');
  await expect(editor.getByLabel('Requested seconds', { exact: true })).toHaveValue('15');
  await expect(editor.getByText(/Generated duration: 15[,.]083 seconds/)).toBeVisible();
  await expect(editor.getByLabel('Voice mode')).toHaveCount(0);
  await expect(editor.getByLabel('Save to look')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Generate images', exact: true })).not.toBeVisible();
  expect((await library(request, id)).reelDrafts).toHaveLength(0);
  await editor.getByRole('button', { name: 'Manage reel references' }).click();
  const pictures = page.locator('.reel-pictures-dialog');
  await pictures.locator(`[data-reference="${asset.id}/${asset.images[0].id}"]`).click();
  if (narrow) await pictures.getByRole('tab', { name: 'Selected references (1)', exact: true }).click();
  await cropReference(page, pictures);
  await pictures.getByRole('button', { name: 'Customize', exact: false }).click();
  await pictures.getByRole('textbox', { name: 'Composition preservation override', exact: true }).fill(`Preserve the brickwork and doorway (${narrow ? 'narrow' : 'desktop'} study).`);
  await pictures.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await editor.getByLabel('Reel name', { exact: true }).fill('Study turn');

  const prompt = editor.getByRole('textbox', { name: 'H3 prompt', exact: true });
  await expect(prompt).toBeEmpty();
  await editor.getByRole('button', { name: 'Reel assistance', exact: true }).click();
  const assist = page.locator('.ai-assist-dialog');
  await expect(assist.getByLabel('Camera preset')).toHaveValue('EnvironmentTurn');
  await expect(assist.getByLabel('Camera direction')).toHaveValue('Right');
  await expect(assist.getByText(/Use keyframes to reference all angles/)).toBeVisible();
  const directions = 'Turn slowly through the room. Pause briefly facing the window.';
  await assist.getByLabel('Instructions', { exact: true }).fill(directions);
  await assist.locator('.model-chip').click();
  await page.getByRole('combobox', { name: 'Text model', exact: true }).selectOption({ label: 'OpenRouter · Alternate mock model' });
  await page.getByRole('button', { name: 'Set as project default', exact: true }).click();
  await assist.getByRole('button', { name: 'Compose pair', exact: true }).click();
  await expect(assist).not.toBeVisible();
  await expect(prompt).toContainText('environment reference reel');
  const capturedContext = (await (await request.get('/fixtures/reel-compositions')).json()).find(c => c.context.environment?.assetId === asset.id);
  expect(capturedContext.context.environment.visualNotes).toBe(asset.description);
  expect(capturedContext.context.environment.preservationGuidance).toBe(asset.preservationGuidance);
  expect(capturedContext.images[0]).toEqual({ width: 32, height: 40 });
  expect(capturedContext.context.presetViews).toContain('360°');
  const draft = (await library(request, id)).reelDrafts[0];
  expect(draft.presetVersion).toBe('environment-reel-v1'); expect(draft.voiceMode).toBe(2); // Silent in fixture HTTP JSON.
  expect(draft.prompt).not.toContain('<Audio'); expect(draft.prompt).not.toContain('<d>');
  expect(draft.useGuidance).toContain('spatial layout');
  await page.reload(); await tools(page);

  await expect(prompt).toHaveText(draft.prompt, { useInnerText: true });
  await expect(editor.getByLabel('Use guidance', { exact: true })).toHaveValue(draft.useGuidance);
  await editor.getByRole('button', { name: 'Generate reel', exact: true }).click();
  if (narrow) await page.getByRole('button', { name: 'Close Asset tools', exact: true }).click();
  await expect.poll(async () => (await library(request, id)).reels.length, { timeout: 45000 }).toBe(1);
  const reel = (await library(request, id)).reels[0];
  expect(reel.generation.recipe.instructions).toBe(directions);
  expect(reel.generation.recipe.prompt).toBe(draft.prompt); expect(reel.generation.snapshot.profile).toBe('environment-reel-v1');
  await page.locator('.asset-media-card[data-media-kind=Reel] .media-select').first().click();
  const player = page.locator('.reel-details-tools video');
  await expect.poll(() => player.evaluate(v => v.readyState)).toBeGreaterThan(0);
  await player.evaluate(async v => { v.muted = true; await v.play(); v.currentTime = 2; });
  await expect.poll(() => player.evaluate(v => v.currentTime)).toBeGreaterThanOrEqual(2);
  await page.locator('.reel-details-tools').getByRole('button', { name: 'Edit details', exact: true }).click();
  const details = page.locator('.reel-details-dialog');
  await expect(details.getByLabel('Saved directions', { exact: true })).toHaveValue(directions);
  await expect(details.getByText(/Use keyframes to reference all angles/)).toBeVisible();
  await expect(details.getByRole('button', { name: 'Manage keyframes…', exact: true })).toBeInViewport();
  await page.screenshot({ path: `artifacts/environment-preset-details-${narrow ? 'narrow' : 'desktop'}.png` });
  await details.getByRole('button', { name: 'Close', exact: true }).click();
  await page.screenshot({ path: `artifacts/environment-reels-${narrow ? 'narrow' : 'desktop'}.png` });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  if (narrow) await page.getByRole('button', { name: 'Close Asset tools', exact: true }).click();
  expect((await (await request.get(`/fixtures/${id}/shots`)).json()).shots).toHaveLength(0);
  await request.post(`/fixtures/${id}/approved`); await request.post(`/fixtures/${id}/production-shot`);
  await page.goto(`/projects/${id}/shots`); await tools(page);
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  const picker = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Manage references', exact: true }) });
  const card = picker.locator(`[data-reel-id="${reel.id}"]`);
  await expect(card).toContainText('Environment reel');
  await card.getByRole('button', { name: `Preview ${reel.name}`, exact: true }).click();
  await expect(card.getByRole('button', { name: `Add reel ${reel.name}`, exact: true })).toBeEnabled();
  await card.locator('.add-reel').click();
  if (narrow) await picker.getByRole('tab', { name: /Selected references/ }).click();
  await expect(picker.getByLabel('Visuals', { exact: true })).toHaveValue('Keyframes');
  await picker.getByLabel('Visuals', { exact: true }).selectOption('FullReel');
  await expect(picker.getByText(/part of a camera turn or route/)).toBeVisible();
  await picker.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(picker).not.toBeVisible();
  const setup = (await (await request.get(`/fixtures/${id}/production`)).json()).compositions[0];
  expect(setup.inputs.videos[0].media.id).toBe(reel.media.id);
  expect(setup.inputs.videos[0].description).toBe(reel.useGuidance);
  expect(setup.inputs.videos[0].useSoundtrack).toBe(false);
  if (narrow) await page.getByRole('button', { name: 'Close Shot tools', exact: true }).click();
  await openShotSetup(page);
  await page.getByRole('button', { name: 'Prompt assistance', exact: true }).click();
  await page.locator('.ai-assist-dialog').getByRole('button', { name: 'Compose prompt', exact: true }).click();
  await expect.poll(async () => (await (await request.get('/fixtures/compositions')).json()).filter(c => c.context.videos?.some(v => v.authorProvidedDescription === reel.useGuidance)).length).toBe(1);
  const shotContext = (await (await request.get('/fixtures/compositions')).json()).find(c => c.context.videos?.some(v => v.authorProvidedDescription === reel.useGuidance)).context;
  expect(shotContext.videos[0].audio).toBeNull(); expect(JSON.stringify(shotContext)).not.toContain(draft.prompt);
});

test('environment custom path keeps authored text and requires instructions only for Assist', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`); await request.post(`/fixtures/${id}/environment-reel-owner`);
  const asset = (await library(request, id)).assets[0];
  await page.goto(`/projects/${id}/assets?assetId=${asset.id}&view=reels`); await tools(page);
  const editor = page.locator('.reel-tools');
  await editor.getByRole('button', { name: 'Manage reel references' }).click();
  const picker = page.locator('.reel-pictures-dialog');
  for (const owner of (await library(request, id)).assets) await picker.locator(`[data-reference="${owner.id}/${owner.images[0].id}"]`).click();
  await picker.getByRole('button', { name: 'Apply changes', exact: true }).click();

  await editor.getByLabel('Use guidance', { exact: true }).fill('My authored layout · café');
  await editor.getByRole('button', { name: 'Reel assistance', exact: true }).click();
  const assist = page.locator('.ai-assist-dialog');
  await assist.getByLabel('Camera preset').selectOption('EnvironmentPath');
  await expect(assist.getByRole('button', { name: 'Compose pair', exact: true })).toBeDisabled();
  await expect(assist.getByText('Describe the custom camera path in Instructions: starting view, route and destination.')).toBeVisible();
  await assist.getByLabel('Instructions', { exact: true }).fill('Move from the doorway toward the window.');
  await assist.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(editor.getByLabel('Use guidance', { exact: true })).toHaveValue('My authored layout · café');
  await page.reload(); await tools(page);

  await editor.getByRole('button', { name: 'Reel assistance', exact: true }).click();
  await expect(assist.getByLabel('Camera preset')).toHaveValue('EnvironmentPath');
  await expect(assist.getByLabel('Instructions', { exact: true })).toHaveValue('Move from the doorway toward the window.');
  expect((await library(request, id)).reelDrafts[0].images).toHaveLength(2);
});
