import { test, expect } from './fixtures.js';
import { openShotSetup, closeShotSetup } from './workspace-tools.js';

for (const narrow of [false, true]) test(`generation footer keeps output local until saved as preset defaults (${narrow ? 'mobile' : 'desktop'})`, async ({ page, request }) => {
  await request.post('/fixtures/generation-setups/reset');
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await request.post(`/fixtures/${id}/production-shot`);
  await request.post(`/fixtures/${id}/production-shot`);
  await page.setViewportSize({ width: narrow ? 390 : 1152, height: narrow ? 844 : 1244 });
  await page.goto(`/projects/${id}/shots`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  const showTools = async () => {
    if (narrow && !await page.locator('.shot-controls').isVisible()) await page.locator('[data-toggle-pane=right]').click();
  };
  await showTools();
  const tools = page.locator('.shot-controls');
  const footer = tools.locator('.generation-output');
  const resolution = footer.getByLabel('Resolution', { exact: true });
  const takes = footer.getByLabel('Takes', { exact: true });
  const library = async () => (await (await request.get('/fixtures/generation-setups')).json()).setups;
  const compositions = async () => (await (await request.get(`/fixtures/${id}/production`)).json()).compositions;
  await expect(tools.getByRole('button', { name: 'Generation settings', exact: true })).toHaveCount(0);
  await expect(tools.getByRole('button', { name: 'Edit generation preset', exact: true })).toBeInViewport();
  await expect(resolution).toBeInViewport();
  await expect(takes).toBeInViewport();
  await expect(tools.getByRole('button', { name: 'Generate takes', exact: true })).toBeInViewport();
  const original = await library();
  await resolution.selectOption('detail');
  await takes.selectOption('3');
  await expect.poll(async () => (await compositions())[0].outputOverrides?.takeCount).toBe(3);
  expect(await library()).toEqual(original);
  await page.reload();
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await showTools();
  await expect(resolution).toHaveValue('detail');
  await expect(takes).toHaveValue('3');
  await openShotSetup(page, 'Preset');
  const preset = page.locator('.shot-setup-dialog');
  await expect(preset.getByLabel('Default resolution', { exact: true })).toHaveValue('preview');
  await preset.getByLabel('Default takes', { exact: true }).selectOption('2');
  await closeShotSetup(page);
  await expect(takes).toHaveValue('3');
  expect((await compositions())[1].takeCount).toBe(2);
  await page.screenshot({ path: `artifacts/generation-output-${narrow ? 'mobile' : 'desktop'}.png` });
  expect(await tools.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await footer.getByRole('button', { name: 'Use preset defaults', exact: true }).click();
  await expect(resolution).toHaveValue('preview');
  await expect(takes).toHaveValue('2');
  await resolution.selectOption('quick');
  await takes.selectOption('4');
  await openShotSetup(page, 'Preset');
  await preset.getByRole('button', { name: 'Save output as preset defaults', exact: true }).click();
  await expect(preset.getByLabel('Default takes', { exact: true })).toHaveValue('4');
  await expect(preset.getByLabel('Default resolution', { exact: true })).toHaveValue('quick');
  await closeShotSetup(page);
  await expect(footer.getByRole('button', { name: 'Use preset defaults', exact: true })).toHaveCount(0);
  const saved = await compositions();
  expect(saved.every(c => c.takeCount === 4 && c.inputs.resolution === 0)).toBe(true);
  await expect(page.locator('#blazor-error-ui')).not.toBeVisible();
});
