import { test, expect } from './fixtures.js';
import { cropImageInput, imageOutput, toolsTab, addImageReference } from './workspace-tools.js';

async function prepare(page, request, prompt = 'Change the coat', count = 2) {
  const project = await (await request.get('/fixtures/new')).json();
  const library = await (await request.post(`/fixtures/${project.id}/images`)).json();
  await page.goto(`/projects/${project.id}/assets`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Image workflow', { exact: true }).selectOption('Flux2Klein9bKv');
  await page.locator('.asset-media-card[data-media-kind=Image] .media-select').click();
  await toolsTab(page, 'Inputs');
  await addImageReference(page, `${library.assets[1].id}/${library.assets[1].images[0].id}`);
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Edit instruction').fill(prompt);
  await imageOutput(page);
  await page.locator('#candidate-count').selectOption(String(count));
  const state = async () => (await (await request.get(`/fixtures/${project.id}`)).json()).assets;
  return { project, library, state };
}

test('edit review compares any pair, discards with Undo, and fits desktop and mobile', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { project, library, state } = await prepare(page, request, 'A very long instruction '.repeat(20));
  await page.getByRole('button', { name: 'Generate edited images', exact: true }).click();
  const modal = page.locator('.image-review-dialog');
  await expect(modal).toBeVisible();
  await expect(modal.locator('.review-metadata-editor')).toBeVisible();
  await expect(modal.getByRole('button', { name: 'Edit details', exact: true })).toHaveCount(0);
  await expect(modal.locator('.review-image-select strong')).toHaveText(['Source', 'Reference 2', 'Take 1', 'Take 2']);
  await expect(modal.getByRole('button', { name: 'View Take 1', exact: true })).toHaveAttribute('aria-pressed', 'true');
  expect(await modal.locator('.review-viewer img').evaluateAll(imgs => imgs.every(i => i.complete && i.naturalWidth > 0))).toBeTruthy();
  for (const [primary, secondary] of [['Take 1', 'Source'], ['Take 1', 'Take 2'], ['Source', 'Reference 2']]) {
    await modal.getByRole('button', { name: `View ${primary}`, exact: true }).click();
    await modal.getByRole('button', { name: `Compare with ${secondary}`, exact: true }).click();
    await expect(modal.locator('.review-wipe')).toBeVisible();
    const slider = modal.getByRole('slider', { name: 'Comparison slider' });
    await slider.focus(); await page.keyboard.press('ArrowRight');
    await expect(slider).toHaveValue('51');
    await modal.getByRole('button', { name: `Compare with ${secondary}`, exact: true }).click();
    await expect(modal.locator('.review-viewer img')).toHaveCount(1);
  }
  await modal.getByRole('button', { name: 'View Take 1', exact: true }).click();
  await modal.getByRole('button', { name: 'Compare with Take 2', exact: true }).click();
  await expect(modal.locator('.review-wipe')).toBeVisible();
  await expect(modal.locator('.image-review-title').getByRole('group', { name: 'Comparison mode', exact: true })).toBeVisible();
  const viewerBox = await modal.locator('.review-viewer').boundingBox();
  const stripBox = await modal.getByRole('group', { name: 'Source images and takes', exact: true }).boundingBox();
  expect(stripBox.y).toBeGreaterThanOrEqual(viewerBox.y + viewerBox.height);
  await expect(modal.locator('.image-review-actions').getByRole('button', { name: 'Save details', exact: true })).toBeInViewport();
  await page.screenshot({ path: 'test-results/image-review-desktop-slider.png' });
  await modal.getByRole('button', { name: 'Side by side', exact: true }).click();
  await expect(modal.locator('.review-viewer.side-by-side')).toBeVisible();
  await page.screenshot({ path: 'test-results/image-review-desktop-pair.png' });
  await modal.getByRole('button', { name: 'Discard Take 1', exact: true }).click();
  await expect(modal.getByRole('button', { name: 'View Take 1', exact: true })).toHaveCount(0);
  await modal.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(modal.getByRole('button', { name: 'View Take 1', exact: true })).toBeVisible();
  await expect(modal.getByRole('button', { name: 'Undo', exact: true })).toHaveCount(0);
  await expect(modal.getByRole('button', { name: 'View Take 2', exact: true })).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(modal).toHaveCount(0);
  expect((await state()).assets[0].images).toHaveLength(3);
  await page.getByRole('button', { name: 'Review latest edit', exact: true }).click();
  await modal.getByRole('button', { name: 'Compare with Take 2', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  expect(await modal.evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy();
  await expect(modal.locator('.image-review-title').getByRole('group', { name: 'Comparison mode', exact: true })).toBeInViewport();
  await expect(modal.locator('.image-review-actions').getByRole('button', { name: 'Save details', exact: true })).toBeInViewport();
  await page.screenshot({ path: 'test-results/image-review-mobile-slider.png' });
  await modal.getByRole('button', { name: 'Side by side', exact: true }).click();
  await expect(modal.locator('.review-viewer.side-by-side')).toBeVisible();
  await page.screenshot({ path: 'test-results/image-review-mobile-pair.png' });
  await modal.getByRole('button', { name: 'Discard Take 1', exact: true }).click();
  await expect(modal.getByRole('button', { name: 'View Take 1', exact: true })).toHaveCount(0);
  await expect(modal.getByRole('button', { name: 'View Take 2', exact: true })).toHaveAttribute('aria-pressed', 'true');
  const saved = await state();
  expect(saved.assets[0].images).toHaveLength(2);
  expect(saved.assets[0].images[0].id).toBe(library.assets[0].images[0].id);
  expect(saved.assets[1].images[0].id).toBe(library.assets[1].images[0].id);
  await modal.getByRole('button', { name: 'Close', exact: true }).focus();
  await page.keyboard.press('Tab');
  expect(await page.evaluate(() => !!document.activeElement.closest('.image-review-dialog'))).toBeTruthy();
  await page.keyboard.press('Escape');
  await expect(modal).toHaveCount(0);
  await expect(page.locator('[data-toggle-pane=right]')).toBeFocused();
  await page.reload(); await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await toolsTab(page, 'Prompt');
  await expect(page.getByRole('button', { name: 'Review latest edit', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close Asset tools', exact: true }).click();
  await page.getByRole('button',{name:/^Preview image/}).first().click();
  await expect(modal.locator('.review-image-row')).toHaveCount(3);
  await expect(modal.getByRole('button', { name: 'Discard Take 2', exact: true })).toBeVisible();
  expect((await state()).assets[0].images).toHaveLength(2);
});

test('review preserves submitted crop and isolates consecutive batches', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { state } = await prepare(page, request);
  await toolsTab(page, 'Inputs');
  await cropImageInput(page,0,2);
  await page.getByRole('button', { name: 'Generate edited images', exact: true }).click();
  const modal = page.locator('.image-review-dialog');
  await expect(modal).toBeVisible();
  await modal.getByRole('button', { name: 'Compare with Source', exact: true }).click();
  await expect(modal.getByRole('button', { name: 'Submitted crops', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(modal.locator('.review-wipe-overlay img')).toHaveAttribute('style', /width:200%/);
  await modal.getByRole('button', { name: 'View Source', exact: true }).click();
  await expect(modal.getByRole('button', { name: 'Full images', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await modal.getByRole('button', { name: 'Close image review' }).click();
  // Generate cleared the references and instruction; the next edit keeps only its source.
  await toolsTab(page, 'Inputs');
  await expect(page.locator('.compact-image-input')).toHaveCount(1);
  await imageOutput(page);
  await page.locator('#candidate-count').selectOption('1');
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Edit instruction').fill('New batch');
  await page.getByRole('button', { name: 'Generate edited images', exact: true }).click();
  await expect(modal.locator('.review-image-select strong')).toHaveText(['Source', 'Take 1']);
  expect((await state()).assets[0].images).toHaveLength(4);
});

test('live review retains partial failures and cancellations while an empty batch stays closed', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { state } = await prepare(page, request, 'FAIL');
  const run = page.getByRole('button', { name: 'Generate edited images', exact: true });
  const modal = page.locator('.image-review-dialog');
  await run.click();
  await expect(modal).toBeVisible();
  await expect(modal.locator('.review-status')).toContainText('Mock edit failed');
  await expect(modal.locator('.review-image-select strong')).toHaveText(['Source', 'Reference 2', 'Take 1']);
  await modal.getByRole('button', { name: 'Close image review' }).click();
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Edit instruction').fill('SLOW');
  await run.click();
  await expect.poll(async () => (await state()).assets[0].images.length).toBe(3);
  await expect(modal).toBeVisible();
  await expect(modal.locator('.review-pending-row')).toHaveCount(1);
  await modal.getByRole('button', { name: 'Cancel remaining', exact: true }).click();
  await expect(modal.locator('.review-pending-row')).toContainText('Cancelled');
  await expect(modal.locator('.review-status')).not.toBeEmpty();
  await modal.getByRole('button', { name: 'Close image review' }).click();
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Edit instruction').fill('EMPTY');
  await run.click();
  await expect(run).toBeEnabled();
  await expect(modal).toHaveCount(0);
  await expect(page.locator('.generation-panel').getByText('The provider ended before returning all requested takes.', { exact: false })).toBeVisible();
});


test('first saved take opens live comparison with pending slots that fill without changing selection', async ({ page, request }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { state } = await prepare(page, request, 'SLOW');
  await page.getByRole('button', { name: 'Generate edited images', exact: true }).click();
  const modal = page.locator('.image-review-dialog');
  await expect(modal).toBeVisible();
  await expect(modal.locator('.review-image-list .review-pending-row')).toHaveCount(1);
  await expect(modal.locator('.review-pending-row')).toContainText('Take 2');
  await expect(modal.locator('.review-pending-row')).toContainText('Generating');
  await expect(modal.locator('.review-pending-row button')).toHaveCount(0);
  await expect(modal.getByRole('button', { name: 'View Take 1', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await modal.getByRole('button', { name: 'Compare with Source', exact: true }).click();
  await expect(modal.locator('.review-wipe')).toBeVisible();
  await expect(modal.getByRole('button', { name: 'Discard Take 1', exact: true })).toBeEnabled();
  await expect(modal.getByRole('button', { name: 'Edit image', exact: true })).toBeEnabled(); // Another edit can queue while this one runs.
  await page.screenshot({ path: 'test-results/image-review-live-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await modal.evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy();
  await expect(modal.getByRole('button', { name: 'Cancel remaining', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/image-review-live-mobile.png' });
  const liveHeight = await modal.locator('.review-viewer').evaluate(el => el.getBoundingClientRect().height);
  await expect(modal.getByRole('button', { name: 'View Take 2', exact: true })).toBeVisible({ timeout: 20000 });
  await expect(modal.locator('.review-pending-row')).toHaveCount(0);
  await expect(modal.locator('.review-live-progress')).toHaveCount(0);
  await expect.poll(() => modal.locator('.review-viewer').evaluate(el => el.getBoundingClientRect().height)).toBeGreaterThan(liveHeight);
  await expect(modal.getByRole('button', { name: 'View Take 1', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(modal.getByRole('button', { name: 'Compare with Source', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(modal.getByRole('button', { name: 'Discard Take 1', exact: true })).toBeEnabled();
  expect((await state()).assets[0].images).toHaveLength(3);
});


test('one more take extends live and completed batches without changing comparison or captured inputs', async ({ page, request }) => {
  test.setTimeout(60000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const { state } = await prepare(page, request, 'SLOW: Keep the original coat');
  await page.locator('.image-generation-settings > summary').click();
  await imageOutput(page);
  await page.locator('#fixed-seed').fill('100');
  await page.getByRole('button', { name: 'Generate edited images', exact: true }).click();
  const modal = page.locator('.image-review-dialog');
  await expect(modal).toBeVisible();
  await modal.getByRole('button', { name: 'Compare with Source', exact: true }).click();
  const divider = modal.getByRole('slider');
  await divider.fill('31');
  const extra = modal.getByRole('button', { name: 'Generate more…', exact: true });
  await extra.click();
  const confirmExtra = page.locator('.repeat-generation-dialog');
  await expect(confirmExtra).toContainText('Keep the original coat');
  await confirmExtra.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(modal.locator('.review-pending-row strong')).toHaveText(['Take 2']);
  await extra.click(); await confirmExtra.getByRole('button', { name: 'Queue 1 image', exact: true }).click();
  await extra.click(); await confirmExtra.getByRole('button', { name: 'Queue 1 image', exact: true }).click();
  await expect(modal.locator('.review-pending-row strong')).toHaveText(['Take 2', 'Take 3', 'Take 4']);
  await expect(modal.getByRole('button', { name: 'View Take 4', exact: true })).toBeVisible({ timeout: 25000 });
  await expect(modal.locator('.review-pending-row')).toHaveCount(0);
  await expect(modal.getByRole('button', { name: 'View Take 1', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(modal.getByRole('button', { name: 'Compare with Source', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(divider).toHaveValue('31');
  await modal.getByRole('button', { name: 'Close image review', exact: true }).click();
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Edit instruction').fill('A new sidebar prompt');
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Image workflow', { exact: true }).selectOption('Krea2');
  await imageOutput(page);
  await page.locator('#fixed-seed').fill('999');
  await page.getByRole('button', { name: 'Review latest edit', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(extra).toBeVisible();
  await extra.focus(); await page.keyboard.press('Enter');
  await confirmExtra.getByRole('button', { name: 'Queue 1 image', exact: true }).click();
  await expect(modal.getByRole('button', { name: 'View Take 5', exact: true })).toBeVisible();
  expect(await modal.evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy();
  const images = (await state()).assets[0].images.filter(i => i.generation);
  expect(images.slice(0, 2).map(i => i.generation.seed)).toEqual([100, 101]);
  expect(new Set(images.map(i => i.generation.seed)).size).toBe(5);
  expect(images.every(i => i.generation.prompt === 'SLOW: Keep the original coat' && i.generation.workflow === 1)).toBeTruthy();
  expect(images.every(i => i.generation.edit.references.length === 2)).toBeTruthy();
  await page.screenshot({ path: 'test-results/one-more-take-mobile.png' });
});
