import { test, expect } from './fixtures.js';
import { toolsTab } from './workspace-tools.js';

test('an open image menu keeps its target when another image arrives in an environment gallery', async ({ page, request }) => {
  test.setTimeout(60000);
  const { id } = await (await request.get('/fixtures/new')).json();
  const library = await (await request.post(`/fixtures/${id}/images?environment=true&patterned=true`)).json();
  const asset = library.assets[1];
  const oldId = asset.images[0].id;
  const images = async () => (await (await request.get(`/fixtures/${id}`)).json()).assets.assets.find(a => a.id === asset.id).images;
  const cards = page.locator('.reference-card');
  const oldCard = cards.filter({ has: page.locator(`img[src$="/images/${oldId}"]`) });
  await page.goto(`/projects/${id}/assets`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await page.locator('.asset-choice').filter({hasText:asset.name}).click();
  await oldCard.locator('.media-select').click();
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Edit instruction',{exact:true}).fill('SLOW: A visibly different image for each candidate.');
  await page.locator('#candidate-count').selectOption('2');
  await page.getByRole('button', { name: 'Generate edited images', exact: true }).click();
  const review = page.locator('.image-review-dialog');
  await expect(review).toBeVisible();
  await expect(cards).toHaveCount(2);
  await review.getByRole('button', { name: 'Close image review', exact: true }).click();
  await oldCard.getByRole('button', { name: 'Image actions', exact: true }).click();
  const menu = page.getByRole('menu', { name: 'Image actions', exact: true });
  await expect(menu).toBeVisible();
  await expect(cards).toHaveCount(3, { timeout: 25000 });
  await expect(menu).toBeVisible();
  const generatedIds = (await images()).filter(i => i.id !== oldId).map(i => i.id).sort();
  await menu.getByRole('menuitem', { name: 'Move to Trash', exact: true }).click();
  await expect.poll(async () => (await images()).map(i => i.id).sort()).toEqual(generatedIds);
  await expect(oldCard).toHaveCount(0);
});

test('new image ordering and card actions agree immediately after background generation', async ({ page, request }) => {
  test.setTimeout(60000);
  const { id } = await (await request.get('/fixtures/new')).json();
  const library = await (await request.post(`/fixtures/${id}/images?patterned=true`)).json();
  const assetId = library.assets[0].id;
  const oldId = library.assets[0].images[0].id;
  const images = async () => (await (await request.get(`/fixtures/${id}`)).json()).assets.assets.find(a => a.id === assetId).images;
  const cards = page.locator('.reference-card');
  const cardFor = imageId => cards.filter({ has: page.locator(`img[src$="/images/${imageId}"]`) });
  await page.goto(`/projects/${id}/assets`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await toolsTab(page, 'Prompt');
  await page.locator('#image-prompt').fill('SLOW: A new solid pink image.');
  await page.getByRole('button', { name: 'Generate images', exact: true }).click();
  const review = page.locator('.image-review-dialog');
  await expect(review).toBeVisible();
  await review.getByRole('button', { name: 'Close image review', exact: true }).click();
  await expect(cards).toHaveCount(2);
  const added = (await images()).find(i => i.id !== oldId);
  await expect(cards.first().locator('img')).toHaveAttribute('src', new RegExp(`/images/${added.id}$`));
  await cardFor(oldId).getByRole('button', { name: 'Image actions', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Move to Trash', exact: true }).click();
  await expect.poll(async () => (await images()).map(i => i.id)).toEqual([added.id]);
  await expect(cardFor(oldId)).toHaveCount(0);
  await expect(cardFor(added.id)).toHaveCount(1);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(cards).toHaveCount(2);
  await expect(cards.first().locator('img')).toHaveAttribute('src', new RegExp(`/images/${added.id}$`));
  const before = await cards.locator('img').evaluateAll(items => items.map(i => i.getAttribute('src')));
  await page.reload();
  await expect(cards).toHaveCount(2);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await expect.poll(() => cards.locator('img').evaluateAll(items => items.map(i => i.getAttribute('src')))).toEqual(before);
});
