import { test, expect } from './fixtures.js';

for (const narrow of [false, true]) test(`project image default (${narrow ? 'narrow' : 'desktop'})`, async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`);
  await page.setViewportSize({ width: narrow ? 390 : 1173, height: narrow ? 844 : 1000 });
  await page.goto(`/projects/${id}/settings`);
  await page.getByRole('button', { name: 'Project image model default', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Project image model', exact: true });
  await dialog.getByLabel('Default image model', { exact: true }).selectOption('Flux2Klein9bKv');
  const save = dialog.getByRole('button', { name: 'Save default', exact: true });
  await save.focus(); await expect(save).toBeInViewport();
  await page.screenshot({ animations: 'disabled', path: `artifacts/project-image-default-${narrow ? 'narrow' : 'desktop'}.png` });
  await save.press('Enter'); await expect(dialog).not.toBeVisible();
  await page.screenshot({ animations: 'disabled', fullPage: true, path: `artifacts/project-model-pickers-${narrow ? 'narrow' : 'desktop'}.png` });
  const preferences = async () => (await (await request.get(`/fixtures/${id}/preferences`)).json());
  expect((await preferences()).imageDefault).toBe(1);
  await page.goto(`/projects/${id}/assets`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  if (narrow && !await page.locator('#asset-image-workflow').isVisible()) await page.getByRole('button', { name: 'Show Asset tools', exact: true }).click();
  await expect(page.locator('#asset-image-workflow')).toHaveValue('Flux2Klein9bKv');
  await expect(page.getByRole('button', { name: 'Project image model default', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Improve prompt', exact: true })).toHaveText('Improve prompt');
  await page.locator('#asset-image-workflow').selectOption('Krea2');
  expect((await preferences()).imageDefault).toBe(1);
  await page.reload();
  await expect(page.locator('#asset-image-workflow')).toHaveValue('Flux2Klein9bKv');
  await page.getByRole('navigation', { name: 'Project navigation' }).getByRole('link', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: 'Project image model default', exact: true }).click();
  await dialog.getByLabel('Default image model', { exact: true }).selectOption('global');
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  expect((await preferences()).imageDefault).toBe(1);
  await page.getByRole('button', { name: 'Project image model default', exact: true }).click();
  await dialog.getByLabel('Default image model', { exact: true }).selectOption('global');
  await save.click(); await expect(dialog).not.toBeVisible();
  expect((await preferences()).imageDefault).toBeNull();
  await page.getByRole('navigation', { name: 'Project navigation' }).getByRole('link', { name: 'Assets', exact: true }).click();
  await expect(page.locator('#asset-image-workflow')).toHaveValue('Krea2');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});
