import { test, expect } from './fixtures.js';
const library = async (request, id) => (await (await request.get(`/fixtures/${id}`)).json()).assets;
for (const narrow of [false, true]) test(`save a reel frame as an ordinary image (${narrow ? 'narrow' : 'desktop'})`, async ({page, request}) => {
  test.setTimeout(90000);
  page.setDefaultTimeout(15000);
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/images`);
  expect((await request.post(`/fixtures/${id}/regeneration-source`)).ok()).toBe(true);
  await expect.poll(async () => (await library(request,id)).reels.length, {timeout:45000}).toBe(1);
  const initial = await library(request,id), reel = initial.reels[0], owner = initial.assets[0];
  await page.setViewportSize({width:narrow?390:1173,height:narrow?844:1000});
  await page.goto(`/projects/${id}/assets?assetId=${owner.id}&view=reels`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready','true');
  if (narrow) {
    await expect(page.locator('.workspace-right')).toBeVisible();
    await page.getByRole('button',{name:'Close Asset tools',exact:true}).click();
    await expect(page.locator('.workspace-right')).not.toBeVisible();
  }
  await page.getByRole('button',{name:`Actions for ${reel.name}`,exact:true}).click();
  await page.getByRole('menuitem',{name:'Manage keyframes…',exact:true}).click();
  const editor = page.locator('.keyframe-editor');
  const exportButton = editor.getByRole('button',{name:'Save frame to Assets…',exact:true});
  await expect(exportButton).toBeEnabled();
  await editor.getByLabel('Frame timeline',{exact:true}).fill('24');
  await expect(editor.locator('.exact-frame')).toHaveAttribute('src',/\/frames\/24\?/);
  await exportButton.click();
  const dialog = page.getByRole('dialog',{name:'Save reel frame to Assets',exact:true});
  await expect(dialog.getByRole('combobox',{name:'Destination asset',exact:true})).toHaveValue(owner.id);
  await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(dialog).not.toBeVisible();
  await expect(exportButton).toBeFocused();
  expect((await library(request,id)).assets[0].images).toHaveLength(owner.images.length);
  await exportButton.click();
  await dialog.getByLabel('Image name',{exact:true}).fill('Chosen reel angle');
  await dialog.getByLabel('What to keep consistent (optional)',{exact:true}).fill('Preserve this viewpoint.');
  const save = dialog.getByRole('button',{name:'Save',exact:true});
  await dialog.getByRole('button',{name:'Cancel',exact:true}).focus();
  await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeInViewport();
  await save.focus(); await expect(save).toBeInViewport();
  await page.screenshot({path:`artifacts/reel-frame-export-${narrow?'narrow':'desktop'}.png`});
  await save.press('Enter'); await expect(dialog).not.toBeVisible();
  await expect(editor.getByRole('link',{name:'View in Assets',exact:true})).toBeVisible();
  const saved = await library(request,id), image = saved.assets[0].images.find(i=>i.name==='Chosen reel angle');
  expect(image).toBeTruthy(); expect(image.source.reelFrame.frame.index).toBe(24);
  expect(image.source.reelFrame.lossless).toBe(true); expect(image.isReference).toBe(false);
  expect(image.preservationGuidance).toBe('Preserve this viewpoint.');
  expect(saved.reels[0].keyframes ?? null).toEqual(reel.keyframes ?? null);
  await editor.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(editor).not.toBeVisible();
  await page.goto(`/projects/${id}/assets?assetId=${owner.id}&imageId=${image.id}`);
  const review = page.locator('.image-review-dialog');
  await expect(review).toBeVisible();
  await review.getByText(/^Saved metadata/).click();
  await expect(review).toContainText('Reel frame'); await expect(review).toContainText('Lossless archive source');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
