import { test, expect } from './fixtures.js';
import { toolsTab, imageOutput } from './workspace-tools.js';

for (const narrow of [false, true]) test(`protected regional edits review before saving (${narrow?'narrow':'desktop'})`, async ({page,request}) => {
  test.setTimeout(120000); page.setDefaultTimeout(12000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log(m.text());});
  const {id}=await (await request.get('/fixtures/new')).json();
  const library=await (await request.post(`/fixtures/${id}/images?patterned=true`)).json();
  const owner=library.assets[0]; const state=async()=>(await (await request.get(`/fixtures/${id}`)).json()).assets;
  await page.setViewportSize({width:narrow?390:1173,height:narrow?844:1000});
  await page.goto(`/projects/${id}/assets`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready','true');
  const closeTools=page.getByRole('button',{name:'Close Asset tools',exact:true});
  if(narrow && await closeTools.isVisible())await closeTools.click();
  await page.locator('.asset-media-card[data-media-kind=Image] .media-select').first().click();
  // Selecting an image opens the narrow tools drawer asynchronously.
  await expect(page.getByLabel('Edit instruction',{exact:true})).toBeVisible();
  await page.getByLabel('Image workflow',{exact:true}).selectOption('Flux2Klein9bKv');
  await page.getByLabel('Edit instruction',{exact:true}).fill('Change the background colour');
  await page.locator('#aspect').selectOption('1:1');
  // Edit area and protection are separate editors on Image 1 in Manage references.
  await page.getByRole('button',{name:'Manage references',exact:true}).click();
  const manager=page.locator('.image-input-manager-dialog');
  await expect(manager).toBeVisible();
  const selected=manager.getByRole('tab',{name:/^Selected references/});
  if(await selected.isVisible())await selected.click();
  const editArea=manager.getByRole('button',{name:'Image 1: Edit area',exact:true});
  await editArea.click();
  const editor=page.locator('.region-editor-dialog');
  await expect(editor.locator('canvas')).toBeVisible();
  await editor.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(editor).not.toBeVisible();
  await expect(editArea).toBeFocused();
  await editArea.click();
  await editor.getByRole('combobox',{name:'Paint',exact:true}).selectOption('edit');
  await editor.getByText('Precise rectangle controls',{exact:true}).click();
  await editor.getByRole('button',{name:'Apply rectangle to selected paint layer',exact:true}).click();
  await expect(editor).toContainText('1 edit strokes');
  await editor.getByRole('button',{name:'Undo',exact:true}).click();await expect(editor).toContainText('0 edit strokes');
  await editor.getByRole('button',{name:'Redo',exact:true}).click();await expect(editor).toContainText('1 edit strokes');
  await editor.getByText('Precise rectangle controls',{exact:true}).click();
  // Exercise actual pointer painting, inside the rectangle so the selection keeps its bounds.
  await editor.getByRole('combobox',{name:'Tool',exact:true}).selectOption('brush');
  const canvas=editor.locator('canvas');const bounds=await canvas.boundingBox();
  await page.mouse.move(bounds.x+bounds.width*.45,bounds.y+bounds.height*.5);
  await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.55,bounds.y+bounds.height*.5,{steps:5});await page.mouse.up();
  await expect(editor).toContainText('2 edit strokes');
  const inputCrop=editor.getByRole('group',{name:'Input crop',exact:true});
  await expect(inputCrop).toContainText('Full image · 64 × 80');
  await inputCrop.getByRole('button',{name:'Crop input to selection',exact:true}).click();
  await expect(inputCrop).toContainText('Cropped · 32 × 40');
  await expect(editor.getByRole('combobox',{name:'View',exact:true})).toHaveValue('input');
  await editor.getByRole('button',{name:'Undo',exact:true}).click();
  await expect(inputCrop).toContainText('Full image · 64 × 80');
  await editor.getByRole('button',{name:'Redo',exact:true}).click();
  await expect(inputCrop).toContainText('Cropped · 32 × 40');
  await inputCrop.getByRole('button',{name:'Adjust input crop',exact:true}).click();
  await expect(editor.getByRole('combobox',{name:'Paint',exact:true})).toHaveValue('context');
  await expect(editor.getByRole('combobox',{name:'Tool',exact:true})).toHaveValue('rectangle');
  await editor.getByRole('combobox',{name:'View',exact:true}).selectOption('input');
  await expect(canvas).toHaveAttribute('width','1024');
  await editor.getByRole('combobox',{name:'View',exact:true}).selectOption('selection');
  const applyArea=editor.getByRole('button',{name:'Apply edit area',exact:true});
  await applyArea.focus(); await expect(applyArea).toBeInViewport();
  await page.screenshot({path:`artifacts/region-editor-${narrow?'narrow':'desktop'}.png`});
  await applyArea.press('Enter');
  await expect(editor).not.toBeVisible();
  const protect=manager.getByRole('button',{name:'Image 1: Protect areas',exact:true});
  await protect.click();
  await expect(editor).toContainText('Protect areas · Image 1');
  await editor.getByText('Precise rectangle controls',{exact:true}).click();
  await editor.getByLabel('Width %',{exact:true}).fill('10');await editor.getByLabel('Height %',{exact:true}).fill('10');
  await editor.getByRole('button',{name:'Protect rectangle',exact:true}).click();
  await expect(editor).toContainText('1 protection strokes');
  await editor.getByRole('button',{name:'Apply protection',exact:true}).click();
  await expect(editor).not.toBeVisible();
  await expect(manager).toContainText('Edit active · Protect active');
  await manager.getByRole('button',{name:'Apply changes',exact:true}).click();
  await expect(manager).not.toBeVisible();
  await imageOutput(page); await page.locator('#aspect').selectOption('1:1');
  await page.locator('#candidate-count').selectOption('2');
  await page.getByRole('button',{name:'Generate edited images',exact:true}).click();
  const review=page.locator('.regional-review-dialog');
  await expect(review).toBeVisible();
  await expect(review.getByRole('button',{name:'Take 2 · Awaiting your review',exact:true})).toBeVisible();
  expect((await state()).assets[0].images).toHaveLength(owner.images.length);
  await review.getByRole('button',{name:'Close',exact:true}).click();
  await page.reload(); await toolsTab(page,'Inputs');
  await page.getByRole('button',{name:'Review latest edit',exact:true}).click();
  await expect(review.getByRole('button',{name:'Save to Assets',exact:true})).toBeEnabled();
  await review.getByLabel('Compare with original',{exact:true}).check();
  await expect(review.getByRole('slider',{name:'Comparison slider',exact:true})).toBeVisible();
  await review.getByLabel('Side by side',{exact:true}).check();
  await expect(review.locator('.review-viewer.side-by-side')).toBeVisible();
  await review.getByLabel('Match original colours',{exact:true}).check();
  await expect(review).toContainText('No reliable colour match');
  await review.getByRole('button',{name:'Choose matching area…',exact:true}).click();
  const matchArea=review.getByRole('region',{name:'Choose matching area',exact:true});
  await expect(matchArea).toBeVisible();
  await matchArea.getByText('Precise matching area controls',{exact:true}).click();
  await matchArea.getByRole('slider',{name:'Matching area zoom',exact:true}).fill('10');
  await matchArea.getByRole('slider',{name:'Matching area horizontal position',exact:true}).fill('0');
  await matchArea.getByRole('button',{name:'Use matching area',exact:true}).click();
  await expect(matchArea).not.toBeVisible();
  await expect(review.getByRole('button',{name:'Choose matching area…',exact:true})).toBeFocused();
  await review.getByRole('slider',{name:'Colour match strength',exact:true}).fill('50');
  await expect(review.getByText('Strength · 50%', { exact: true })).toBeVisible();
  await review.getByRole('button',{name:'Reset colour adjustments',exact:true}).click();
  await expect(review.getByLabel('Match original colours',{exact:true})).not.toBeChecked();
  await expect(review.getByRole('button',{name:'Use surrounding context',exact:true})).not.toBeVisible();
  await review.getByText('Manual adjustments',{exact:true}).click();
  await review.getByRole('slider',{name:'Brightness',exact:true}).fill('-3');
  await review.getByRole('slider',{name:'Warmth',exact:true}).fill('2');
  await review.getByRole('slider',{name:'Tint',exact:true}).fill('1');
  await review.getByLabel('Edge blend',{exact:true}).fill('4');
  await expect(review.getByRole('button',{name:'Save to Assets',exact:true})).toBeEnabled();
  await review.getByRole('button',{name:'Close',exact:true}).click();
  await page.reload(); await toolsTab(page,'Inputs');
  await page.getByRole('button',{name:'Review latest edit',exact:true}).click();
  await review.getByText('Manual adjustments',{exact:true}).click();
  await expect(review.getByRole('slider',{name:'Brightness',exact:true})).toHaveValue('-3');
  await expect(review.getByRole('slider',{name:'Warmth',exact:true})).toHaveValue('2');
  await expect(review.getByRole('slider',{name:'Tint',exact:true})).toHaveValue('1');
  await expect(review.getByLabel('Edge blend',{exact:true})).toHaveValue('4');
  const save=review.getByRole('button',{name:'Save to Assets',exact:true});await save.focus();await expect(save).toBeInViewport();
  await page.screenshot({path:`artifacts/region-review-${narrow?'narrow':'desktop'}.png`});
  await save.press('Enter');
  await expect(review.getByRole('button',{name:'Take 1 · Saved to Assets',exact:true})).toBeVisible();
  await expect(review.getByRole('slider',{name:'Brightness',exact:true})).toBeDisabled();
  expect((await state()).assets[0].images).toHaveLength(owner.images.length+1);
  await review.getByRole('button',{name:'Take 2 · Awaiting your review',exact:true}).click();
  await review.getByRole('button',{name:'Discard result',exact:true}).click();
  await expect(review.getByRole('button',{name:'Take 2 · Discarded',exact:true})).toBeVisible();
  if(!narrow) {
    await review.getByRole('button',{name:'Generate more…',exact:true}).click();
    await page.getByRole('button',{name:'Queue 1 image',exact:true}).click();
    await expect(review.getByRole('button',{name:'Take 3 · Awaiting your review',exact:true})).toBeVisible();
    expect((await state()).assets[0].images).toHaveLength(owner.images.length+1);
  }
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
