import { test, expect } from './fixtures.js';
test.beforeEach(async ({ request }) => { await request.post('/fixtures/generation-setups/reset'); });
import { openShotSetup, closeShotSetup } from './workspace-tools.js';

test('earlier setup inputs survive migration and can be restored and undone without changing generation settings', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await request.post(`/fixtures/${id}/images`);
  await request.post(`/fixtures/${id}/production-shot`);
  expect((await request.post(`/fixtures/${id}/legacy-setup-inputs`)).ok()).toBe(true);
  const state = async () => (await request.get(`/fixtures/${id}/production`)).json();
  await page.goto(`/projects/${id}/shots`);
  await openShotSetup(page, 'Generation settings');
  const dialog = page.locator('.shot-setup-dialog');
  await dialog.getByLabel('Default takes', { exact: true }).selectOption('3');
  await openShotSetup(page);
  const editor = page.getByRole('textbox', { name: 'H3 prompt', exact: true });
  await expect(editor).toHaveText('The earlier default prompt.');
  await expect(dialog.getByLabel('Named setup', { exact: true })).toBeHidden();
  await dialog.getByText('Earlier setup prompts and references', { exact: true }).click();
  await dialog.locator('.earlier-setup-content').getByText('Earlier alternative', { exact: true }).click();
  await dialog.getByRole('button', { name: 'Use this prompt and references', exact: true }).click();
  await expect(editor).toHaveText('A different preserved prompt.');
  await expect.poll(async () => (await state()).compositions.map(c => c.prompt)).toEqual(['A different preserved prompt.', 'A different preserved prompt.']);
  expect((await state()).compositions.every(c => c.inputs.images.length === 0)).toBe(true);
  expect((await state()).compositions[0].takeCount).toBe(3);
  await dialog.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(editor).toHaveText('The earlier default prompt.');
  await expect.poll(async () => (await state()).compositions.map(c => c.inputs.images.length)).toEqual([1, 1]);
  expect((await state()).compositions[0].takeCount).toBe(3);
  await openShotSetup(page, 'Generation settings');
  const alternative = (await state()).compositions[1];
  await dialog.getByLabel('Named setup', { exact: true }).selectOption(alternative.generationSetupId);
  await expect(dialog.getByLabel('Default resolution', { exact: true })).toHaveValue('detail');
  await openShotSetup(page);
  await expect(editor).toHaveText('The earlier default prompt.');
  await closeShotSetup(page);
  await page.reload(); await openShotSetup(page);
  await expect(editor).toHaveText('The earlier default prompt.');
  expect((await state()).earlierSetupContent[0].content.prompt).toBe('A different preserved prompt.');
  await expect(page.locator('#blazor-error-ui')).not.toBeVisible();
});
