import { planningComposer, submitPlanning } from './text-assistance-tools.js';
import { test, expect } from './fixtures.js';

test('fenced shot responses require a complete result and explicit acceptance', async ({ page, request }) => {
  const project = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${project.id}/approved`);
  const saved = async () => (await (await request.get(`/fixtures/${project.id}/shots`)).json()).shots;
  await page.goto(`/projects/${project.id}/shots`);
  await expect(page.locator('.shots-heading')).toHaveAttribute('data-interactive', 'true');
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  const plan = page.locator('.shot-planning-dialog');
  const instructions = planningComposer(page).getByLabel('Directing instructions (optional)');
  const apply = plan.getByRole('button', { name: 'Add reviewed shots' });
  await instructions.fill('FENCED TRUNCATED');
  await submitPlanning(page);
  await expect(plan).toContainText('incomplete output cannot be applied');
  await expect(apply).toBeDisabled();
  expect(await saved()).toHaveLength(0);
  await plan.getByRole('button', { name: 'New breakdown', exact: true }).click();
  await instructions.fill('FENCED');
  await submitPlanning(page);
  await expect(apply).toBeEnabled();
  expect(await saved()).toHaveLength(0);
  await plan.locator('summary').filter({ hasText: 'Response details' }).click();
  await expect(plan.locator('pre')).toContainText('```json');
  await expect(plan).toContainText('You called?');
  await apply.click();
  await expect.poll(async () => (await saved()).length).toBe(1);
  await expect(page.getByLabel('Exact dialogue')).toHaveValue('You called?');
});

test('new coverage drafts retain cast and exact dialogue without assigning library looks', async ({ page, request }) => {
  const project = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${project.id}/images`);
  await request.post(`/fixtures/${project.id}/approved`);
  await page.goto(`/projects/${project.id}/shots`);
  await page.getByRole('button', { name: 'Draft shots', exact: true }).click();
  const plan = page.locator('.shot-planning-dialog');
  await submitPlanning(page);
  await expect(plan.getByRole('button', { name: 'Add reviewed shots' })).toBeEnabled();
  await expect(plan.getByLabel('Character name')).toHaveValue('JUNIPER');
  await expect(plan.getByLabel('Character asset', { exact: true })).toHaveCount(0);
  await plan.getByRole('button', { name: 'Add reviewed shots' }).click();
  await expect(plan).not.toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Exact dialogue')).toHaveValue('You called?');
  const shot = (await (await request.get(`/fixtures/${project.id}/shots`)).json()).shots[0];
  expect(shot.characters[0].appearance).toBeNull();
  expect(shot.planning.profile).toBe('shot-coverage-v3');
});
