import { test, expect } from './fixtures.js';
import { toolsTab, closeShotSetup } from './workspace-tools.js';

test('move selected takes to another shot with provenance and regeneration intact', async ({ page, request }) => {
  test.setTimeout(120000);
  await page.setViewportSize({ width: 1173, height: 1000 });
  const { id } = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${id}/approved`);
  await request.post(`/fixtures/${id}/production-shot`);
  expect((await request.post(`/fixtures/${id}/take-generation-setup`)).ok()).toBe(true);
  const state = async () => (await request.get(`/fixtures/${id}/shots`)).json();
  await page.goto(`/projects/${id}/shots`);
  await toolsTab(page, 'Generate');
  await closeShotSetup(page);
  await page.getByRole('button', { name: 'Generate takes', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length, { timeout: 45000 }).toBe(2);
  await page.locator('.shot-review-dialog').getByRole('button', { name: 'Close', exact: true }).click();
  const original = await state();
  await page.getByRole('button', { name: '+ Shot', exact: true }).click();
  await expect.poll(async () => (await state()).shots.length).toBe(2);
  const destination = (await state()).shots[1];
  await page.locator(`[data-shot-id='${original.shots[0].id}']`).click();
  const takesTab = page.locator('[data-workspace-group=center]').getByRole('tab', { name: 'Takes', exact: true });
  await takesTab.click();
  const cards = page.locator('.unified-take-card');
  await expect(cards).toHaveCount(2);
  await page.getByRole('button', { name: 'Select multiple', exact: true }).click();
  await page.getByLabel('Select take 1', { exact: true }).check();
  await page.getByLabel('Select take 2', { exact: true }).check();
  await page.getByRole('button', { name: 'Move to shot…', exact: true }).click();
  const dialog = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Move takes to another shot' }) });
  await expect(dialog.getByLabel('Destination shot')).toHaveValue(destination.id);
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect((await state()).takes.map(t => t.shotId)).toEqual(original.takes.map(t => t.shotId));
  await page.getByRole('button', { name: 'Move to shot…', exact: true }).click();
  await dialog.getByRole('button', { name: 'Move takes', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect.poll(async () => (await state()).takes.filter(t => t.shotId === destination.id).length).toBe(2);
  expect((await state()).takes).toEqual(original.takes.map(t => ({ ...t, shotId: destination.id })));
  await expect(cards).toHaveCount(2);
  await page.reload();
  await expect(cards).toHaveCount(2);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/take-moves-narrow.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await cards.first().getByRole('button', { name: 'Regenerate…', exact: true }).click();
  await page.locator('.video-regeneration-dialog').getByRole('button', { name: 'Generate take', exact: true }).click();
  await expect.poll(async () => (await state()).takes.length, { timeout: 45000 }).toBe(3);
  const generated = (await state()).takes.find(t => !original.takes.some(o => o.id === t.id));
  expect(generated.shotId).toBe(destination.id);
  expect(generated.snapshot.shot.id).toBe(original.shots[0].id);
});
