import { modelOptions } from './text-assistance-tools.js';
import { test, expect } from './fixtures.js';

const section = (page, name) => page.getByRole('tablist', { name: 'AI settings sections' }).getByRole('tab', { name, exact: true });
const provider = (page, name) => page.getByRole('tablist', { name: 'Text model providers' }).getByRole('tab', { name, exact: true });
const snapshot = async request => (await request.get('/fixtures/text-catalog')).json();

test.beforeEach(async ({ request }) => { await request.post('/fixtures/text-catalog?enabled=true&failed=false'); });
test.afterEach(async ({ request }) => { await request.post('/fixtures/text-catalog?enabled=false&failed=false'); });

test('untested OpenRouter stars offer a keyboard accessible warning, test shortcut and explicit override', async ({ page, request }) => {
  const before = await snapshot(request);
  await page.goto('/settings/ai?tab=text&provider=openrouter');
  await expect(page.locator('h1')).toBeFocused();
  await page.getByLabel('Search text models', { exact: true }).fill('Catalog model 29');
  const row = page.locator('.text-model-row');
  const star = row.getByRole('button', { name: 'Star Catalog model 29', exact: true });
  const warning = row.getByRole('region', { name: 'Test before starring', exact: true });
  const dialog = page.getByRole('dialog', { name: 'Model details & test', exact: true });
  await expect(row).toHaveCount(1);
  await expect(row).toContainText('Not tested');
  const jobsBefore = (await (await request.get('/fixtures/ai-jobs')).json()).length;
  await star.focus(); await page.keyboard.press('Enter');
  await expect(warning.getByRole('alert')).toContainText('Catalog discovery does not test generation');
  expect((await snapshot(request)).starredTextModels).toEqual(before.starredTextModels);
  await warning.getByRole('button', { name: 'Cancel', exact: true }).focus(); await page.keyboard.press('Enter');
  await expect(warning).toHaveCount(0);
  await star.click();
  await page.setViewportSize({ width: 1173, height: 1272 });
  await page.screenshot({ path: 'artifacts/openrouter-star-warning-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(warning.getByRole('button', { name: 'Test model', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await warning.scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'artifacts/openrouter-star-warning-mobile.png' });
  await warning.getByRole('button', { name: 'Star anyway', exact: true }).click();
  await expect(row.getByRole('button', { name: 'Unstar Catalog model 29', exact: true })).toBeVisible();
  expect((await (await request.get('/fixtures/ai-jobs')).json()).length).toBe(jobsBefore);
  await row.getByRole('button', { name: 'Unstar Catalog model 29', exact: true }).click();
  await expect(star).toBeVisible(); await star.click();
  await warning.getByRole('button', { name: 'Test model', exact: true }).click();
  await expect(dialog).toBeVisible();
  expect((await (await request.get('/fixtures/ai-jobs')).json()).length).toBe(jobsBefore);
  await dialog.getByRole('button', { name: 'Run benchmark · 2,048 total tokens', exact: true }).click();
  await expect(dialog).toContainText('Test result saved.');
  await dialog.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(row).toContainText('Benchmark completed');
  await star.click();
  await expect(row.getByRole('button', { name: 'Unstar Catalog model 29', exact: true })).toBeVisible();
  await expect(warning).toHaveCount(0);
  await page.reload();
  await expect(page.locator('h1')).toBeFocused();
  await page.getByLabel('Search text models', { exact: true }).fill('Catalog model 29');
  await expect(row).toHaveCount(1);
  await expect(row).toContainText('Benchmark completed');
  await row.getByRole('button', { name: 'Unstar Catalog model 29', exact: true }).click();
  await expect(star).toBeVisible();
  const after = await snapshot(request);
  expect(after.starredTextModels).toEqual(before.starredTextModels);
  expect(after.defaultBackend).toBe(before.defaultBackend); expect(after.openRouterModel).toBe(before.openRouterModel);
});

test('ComfyUI generation defaults retain drafts and save independently of shared timeouts', async ({ page }) => {
  await page.goto('/settings/ai?tab=text&provider=comfyui');
  await expect(page.locator('h1')).toBeFocused();
  await page.getByText('ComfyUI defaults', { exact: true }).click();
  const form = page.locator('#comfy-text-settings-form');
  const tokens = page.getByLabel('Maximum output tokens', { exact: true });
  const original = await tokens.inputValue();
  const next = original === '4096' ? '8192' : '4096';
  await tokens.fill(next);
  await provider(page, 'OpenRouter').click();
  await expect(tokens).toHaveCount(0);
  await provider(page, 'Defaults & profiles').click();
  await expect(tokens).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Request timeout' })).toBeVisible();
  const timeout = page.getByLabel('Text inactivity timeout in seconds', { exact: true });
  const timeoutBefore = await timeout.inputValue();
  const timeoutDraft = timeoutBefore === '505' ? '506' : '505';
  await timeout.fill(timeoutDraft);
  await provider(page, 'ComfyUI').click();
  await expect(tokens).toHaveValue(next);
  await form.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(tokens).toHaveValue(original);
  await tokens.fill(next);
  await form.getByRole('button', { name: 'Save generation defaults', exact: true }).click();
  await expect(page.getByText('ComfyUI generation defaults saved.', { exact: true })).toBeVisible();
  await provider(page, 'Defaults & profiles').click(); await expect(timeout).toHaveValue(timeoutDraft);
  await page.reload(); await expect(page.locator('h1')).toBeFocused();
  await provider(page, 'Defaults & profiles').click();
  await expect(timeout).toHaveValue(timeoutBefore);
  await provider(page, 'ComfyUI').click(); await page.getByText('ComfyUI defaults', { exact: true }).click(); await expect(tokens).toHaveValue(next);
  await page.setViewportSize({ width: 1173, height: 1272 });
  await page.screenshot({ path: 'artifacts/comfy-text-settings-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'artifacts/comfy-text-settings-mobile.png', fullPage: true });
  await tokens.fill(original);
  await form.getByRole('button', { name: 'Save generation defaults', exact: true }).click();
  await expect(page.getByText('ComfyUI generation defaults saved.', { exact: true })).toBeVisible();
});

test('provider catalogs preserve filters, pages, aliases and keyboard focus across navigation', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  const { slug } = await (await request.get(`/fixtures/${id}/project-route`)).json();
  const origin = `/projects/${slug}/assets?view=grid#focus`;
  const before = await snapshot(request);
  await page.setViewportSize({ width: 1173, height: 1272 });
  await page.goto(`/settings/ai?tab=text&provider=openrouter&returnUrl=${encodeURIComponent(origin)}`);
  await expect(provider(page, 'OpenRouter')).toHaveAttribute('aria-selected', 'true');
  await expect(page.locator('.text-model-row')).toHaveCount(25);
  await expect(page.getByRole('button', { name: 'Set default', exact: true })).toHaveCount(0);
  await provider(page, 'Defaults & profiles').click();
  const defaultBefore = await page.locator('#global-text-default').inputValue();
  await provider(page, 'OpenRouter').click();
  await expect.poll(async () => (await snapshot(request)).checks.OpenRouter).toBe((before.checks.OpenRouter || 0) + 1);
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.locator('.text-model-expand').first().click();
  await page.getByLabel('Alias', { exact: true }).fill('Unfinished alias');
  await provider(page, 'OpenRouter').focus(); await page.keyboard.press('Home');
  await expect(provider(page, 'ComfyUI')).toBeFocused();
  await expect(page.getByLabel('Alias', { exact: true })).toHaveCount(0);
  await page.keyboard.press('Tab');
  await expect(page.getByRole('button', { name: 'Refresh ComfyUI models', exact: true })).toBeFocused();
  await page.getByLabel('Search text models', { exact: true }).fill('Mock script');
  await section(page, 'Image models').click(); await section(page, 'Text models').click();
  await expect(page.getByLabel('Search text models', { exact: true })).toHaveValue('Mock script');
  await provider(page, 'ComfyUI').focus(); await page.keyboard.press('ArrowDown');
  await expect(provider(page, 'OpenRouter')).toBeFocused();
  await expect(page.getByText('Page 2 of 2', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Alias', { exact: true })).toHaveValue('Unfinished alias');
  await expect.poll(async () => (await snapshot(request)).checks.OpenRouter).toBe((before.checks.OpenRouter || 0) + 1);
  await expect(page.locator('.writing-back')).toHaveAttribute('href', origin);
  await provider(page, 'Defaults & profiles').click();
  await expect(page.locator('#global-text-default')).toHaveValue(defaultBefore);
  await provider(page, 'OpenRouter').click();
  await page.getByRole('button', { name: 'Cancel alias', exact: true }).click();
  await page.locator('[role=columnheader][data-column=input] button').click();
  await expect(page.locator('.text-model-expand').first()).toHaveText('Free writing model');
  await page.locator('.text-model-expand').first().click();
  await page.screenshot({ path: 'artifacts/text-settings-desktop.png', fullPage: true });
  await page.reload();
  // The provider selection is page state; a reload opens the first provider.
  await expect(provider(page, 'ComfyUI')).toHaveAttribute('aria-selected', 'true');
  await provider(page, 'OpenRouter').click();
  await expect(page.locator('#model-sort')).toHaveValue('name');
  await expect(page.locator('.writing-back')).toHaveAttribute('href', origin);
});

test('prices sort across pages and failed discovery keeps a stale catalog with one error', async ({ page, request }) => {
  await page.goto('/settings/ai?tab=text&provider=openrouter');
  await expect(page.locator('h1')).toBeFocused();
  await expect(page.locator('.text-model-row')).toHaveCount(25);
  await page.locator('[role=columnheader][data-column=input] button').click();
  await expect(page.locator('.text-model-expand').first()).toHaveText('Free writing model');
  await expect(page.locator('.text-model-row').first()).toContainText('Free text');
  await expect(page.locator('.text-model-expand').nth(1)).toHaveText('Catalog model 30');
  await expect(page.locator('.text-model-row').nth(1).locator('[role=cell][data-column=input]')).toContainText('$0.1');
  await expect(page.locator('.text-model-row').nth(1)).toContainText('Image input');
  await expect(page.locator('.text-model-row').nth(1)).toContainText('Reasoning');
  await page.locator('.text-model-expand').nth(1).click();
  await expect(page.locator('.text-model-details')).toContainText('$0.005 / search');
  await expect(page.locator('.text-model-details')).toContainText('Maximum output');
  await page.locator('[role=columnheader][data-column=context] button').click();
  await expect(page.locator('.text-model-row').first()).toContainText('Conditional rates');
  await page.locator('.text-model-expand').first().click();
  await expect(page.locator('.text-model-details')).toContainText('Rates vary with conditions');
  await request.post('/fixtures/text-catalog?enabled=true&failed=true');
  await page.getByRole('button', { name: 'Refresh OpenRouter models', exact: true }).click();
  await expect(page.getByText('Mock OpenRouter connection unavailable', { exact: true })).toHaveCount(1);
  await expect(page.locator('.text-provider-status')).toContainText('may be out of date');
  await expect(page.locator('.text-model-row')).toHaveCount(25);
  await expect(page.locator('.model-star').first()).toBeDisabled();
  await request.post('/fixtures/text-catalog?enabled=true&failed=false');
  await page.getByRole('button', { name: 'Refresh OpenRouter models', exact: true }).click();
  await expect(page.locator('.text-provider-status')).not.toContainText('may be out of date');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/text-settings-mobile.png', fullPage: true });
  await page.screenshot({ path: 'artifacts/text-settings-mobile-viewport.png' });
  const bounds = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }));
  expect(bounds.scroll).toBeLessThanOrEqual(bounds.width);
  const sidebar = await page.getByRole('tablist', { name: 'Text model providers' }).boundingBox();
  const panel = await page.locator('.text-provider-content').boundingBox();
  expect(sidebar.y + sidebar.height).toBeLessThan(panel.y);
});

test('saved aliases reach studio pickers and clearing restores the provider name', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  const before = await snapshot(request);
  await page.goto('/settings/ai?tab=text&provider=openrouter');
  await expect(page.locator('h1')).toBeFocused();
  await page.getByLabel('Search text models', { exact: true }).fill('Alternate mock');
  await expect(page.locator('.text-model-expand')).toHaveCount(1);
  await page.locator('.text-model-expand').click();
  await page.getByLabel('Alias', { exact: true }).fill('My story writer');
  await page.getByRole('button', { name: 'Save alias', exact: true }).click();
  await expect(page.locator('.text-model-expand')).toHaveText('My story writer');
  await provider(page, 'Defaults & profiles').click();
  await expect(page.locator('#global-text-default')).toContainText('My story writer');
  await page.goto(`/projects/${id}/script`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await modelOptions(page);
  await expect(page.getByRole('combobox', { name: 'Text model', exact: true })).toContainText('My story writer');
  await page.getByRole('combobox', { name: 'Text model', exact: true }).selectOption('OpenRouter\nmock/alternate\n');
  await expect(page.locator('.ai-assist-dialog')).toContainText('For this request only');
  await page.getByRole('link', { name: 'Manage models', exact: true }).first().click();
  await expect(page.locator('h1')).toBeFocused();
  await provider(page, 'OpenRouter').click();
  await expect(provider(page, 'OpenRouter')).toHaveAttribute('aria-selected', 'true');
  await page.getByLabel('Search text models', { exact: true }).fill('My story writer');
  await expect(page.locator('.text-model-expand')).toHaveCount(1);
  await page.locator('.text-model-expand').click();
  await page.getByLabel('Alias', { exact: true }).fill('');
  await page.getByRole('button', { name: 'Save alias', exact: true }).click();
  await page.getByLabel('Search text models', { exact: true }).fill('mock/alternate');
  await expect(page.locator('.text-model-expand')).toHaveText('Alternate mock model');
  const after = await snapshot(request);
  expect(after.defaultBackend).toBe(before.defaultBackend); expect(after.openRouterModel).toBe(before.openRouterModel);
  expect(after.starredTextModels).toEqual(before.starredTextModels);
});

test('column headings toggle sort direction by keyboard and mobile has equivalent controls', async ({ page }) => {
  await page.setViewportSize({ width: 1173, height: 1272 });
  await page.goto('/settings/ai?tab=text&provider=openrouter');
  await expect(page.locator('h1')).toBeFocused();
  const heading = key => page.locator(`[role=columnheader][data-column=${key}]`);
  await expect(heading('name')).toHaveAttribute('aria-sort', 'ascending');
  await expect(page.getByRole('columnheader')).toHaveCount(6);
  await heading('added').getByRole('button').focus(); await page.keyboard.press('Enter');
  await expect(heading('added')).toHaveAttribute('aria-sort', 'descending');
  await expect(page.locator('.text-model-expand').first()).toHaveText('Catalog model 30');
  await expect(page.locator('.text-model-row').first().locator('[data-column=added]')).toContainText('2026-01-31');
  await page.keyboard.press('Space');
  await expect(heading('added')).toHaveAttribute('aria-sort', 'ascending');
  await expect(page.locator('.text-model-expand').first()).toHaveText('Catalog model 01');
  await heading('popularity').getByRole('button').click();
  await expect(page.locator('.text-model-row').first().locator('[data-column=popularity]')).toContainText('#1');
  await heading('popularity').getByRole('button').click();
  await expect(heading('popularity')).toHaveAttribute('aria-sort', 'descending');
  await expect(page.locator('.text-model-row').first().locator('[data-column=popularity]')).toContainText('#30');
  await provider(page, 'ComfyUI').click();
  await expect(page.getByRole('columnheader')).toHaveCount(4);
  await provider(page, 'OpenRouter').click();
  await expect(heading('popularity')).toHaveAttribute('aria-sort', 'descending');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('columnheader')).toHaveCount(0);
  await expect(page.getByLabel('Sort', { exact: true })).toHaveValue('popularity');
  await page.getByRole('button', { name: 'Switch to ascending order', exact: true }).click();
  await expect(page.locator('.text-model-expand').first()).toHaveText('Catalog model 01');
  await page.getByLabel('Sort', { exact: true }).selectOption('added');
  await expect(page.locator('.text-model-expand').first()).toHaveText('Catalog model 30');
  await page.setViewportSize({ width: 1173, height: 1272 });
  await expect(heading('added')).toHaveAttribute('aria-sort', 'descending');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
