import { test, expect } from './fixtures.js';

test('advanced video catalog keeps selected community files through filtering, save and reload', async ({ page }) => {
  await page.goto('/settings/ai');
  await expect(page.locator('h1')).toBeFocused();
  await page.getByRole('tab', { name: 'Video models', exact: true }).click();
  const panel = page.locator('.video-model-form');
  const attention = panel.getByLabel('H3 dense attention', { exact: true });
  await panel.locator('.video-performance-settings > summary').click();
  await expect(panel.getByRole('checkbox', { name: /Sol-Attn/ })).toHaveCount(0);
  await expect(panel.getByLabel('H3 archive compression')).toHaveCount(0);
  await expect(panel.locator('.video-preset-setup')).toHaveCount(10);
  await expect(attention).toHaveValue('ServerDefault');
  await attention.selectOption('Sage');
  await panel.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(attention).toHaveValue('ServerDefault');
  await attention.selectOption('Kitchen');
  await panel.locator('[data-preset=turbo8] > summary').click();
  await panel.locator('[data-preset=turbo4] > summary').click();
  const encoder = panel.getByLabel('H3 Encoder', { exact: true });
  const turbo8 = panel.getByLabel('turbo8 checkpoint', { exact: true });
  const turbo4 = panel.getByLabel('turbo4 checkpoint', { exact: true });
  const eightStepFile = 'h3/minimax_h3_ref2v_turbo_8step_v1.0_768p_comfyui_bf16.safetensors';
  const toggle = panel.getByRole('checkbox', { name: 'Show all installed files (advanced)' });
  const custom = 'custom/renamed-h3-encoder.safetensors';
  await panel.getByRole('button', { name: 'Refresh video models' }).click();
  await expect(turbo8.locator('option', { hasText: eightStepFile })).toHaveCount(1);
  await expect(turbo4.locator('option', { hasText: '8step' })).toHaveCount(0);
  await turbo8.selectOption(eightStepFile);
  await expect(encoder.locator('option', { hasText: custom })).toHaveCount(0);
  await toggle.focus();
  await page.keyboard.press('Space');
  await expect(toggle).toBeChecked();
  await expect(encoder.locator('option', { hasText: custom })).toHaveCount(1);
  await encoder.selectOption(custom);
  await toggle.uncheck();
  await expect(encoder).toHaveValue(custom);
  await panel.getByRole('button', { name: 'Save MiniMax H3' }).click();
  await expect(panel.getByText('MiniMax H3 saved.', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('h1')).toBeFocused();
  await page.getByRole('tab', { name: 'Video models', exact: true }).click();
  await panel.locator('.video-performance-settings > summary').click();
  await panel.locator('[data-preset=turbo8] > summary').click();
  await expect(attention).toHaveValue('Kitchen');
  await expect(toggle).not.toBeChecked();
  await expect(panel.locator('.video-catalog-toggle').first()).toHaveCSS('display', 'flex');
  await expect(encoder).toHaveValue(custom);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(turbo8).toHaveValue(eightStepFile);
  await expect(toggle).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/video-settings-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'test-results/video-settings-desktop.png', fullPage: true });
  // Reopening keeps the saved selection, while Cancel discards a new form draft.
  await panel.getByRole('button', { name: 'Refresh video models' }).click();
  await toggle.check();
  await turbo8.selectOption('custom/renamed-ref2va-turbo.safetensors');
  await panel.getByLabel('H3 Model', { exact: true }).selectOption('custom/renamed-ref2va.safetensors');
  await panel.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(panel.getByLabel('H3 Model', { exact: true })).not.toHaveValue('custom/renamed-ref2va.safetensors');
  await expect(turbo8).toHaveValue(eightStepFile);
  // Keep the shared mock settings neutral for subsequent browser walkthroughs.
  await attention.selectOption('ServerDefault');
  await panel.getByRole('button', { name: 'Save MiniMax H3' }).click();
});
