import { test, expect } from './fixtures.js';
import { cropReference, editShotReference, imageOutput, toolsTab } from './workspace-tools.js';

test('long scripts scroll inside the paper and retain pane sizes, text and undo', async ({ page, request }) => {
  const project = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${project.id}/large`);
  await page.setViewportSize({ width: 1440, height: 950 });
  await page.addInitScript(() => {
    const key = 'lumibelle.workspace.Script.v1';
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify({left:200,right:340,leftCollapsed:true,rightCollapsed:true}));
  });
  await page.goto(`/projects/${project.id}/script`);
  const workspace = page.locator('.studio-workspace');
  await expect(workspace).toHaveAttribute('data-ready', 'true');
  const paper = page.locator('.workspace-center .workspace-pane-body'), left = page.locator('.workspace-left .workspace-pane-body');
  const lastHeading = page.locator('.outline-title').last();
  await lastHeading.click();
  await expect.poll(() => paper.evaluate(el => el.scrollTop)).toBeGreaterThan(1000);
  expect(await page.evaluate(() => scrollY)).toBe(0);
  await expect(page.locator('.script-toolbar')).toBeInViewport();
  await expect(page.getByRole('button', { name: 'Revise', exact: true })).toBeInViewport();
  const scroll = await paper.evaluate(el => el.scrollTop), leftScroll = await left.evaluate(el => el.scrollTop);
  const splitter = page.getByRole('separator', { name: 'Outline', exact: true });
  await splitter.focus(); await page.keyboard.press('ArrowRight');
  await expect(splitter).toHaveAttribute('aria-valuenow', '210');
  // Wider outline rows wrap less; preserve the visible scene, not the pixel offset.
  await expect(lastHeading).toBeInViewport();
  // Resizing may reflow words but must not send the reader back to the beginning.
  expect(await paper.evaluate(el => el.scrollTop)).toBeGreaterThan(scroll / 2);
  await page.getByLabel('Instructions', { exact: true }).fill('Keep the intention and tighten the wording.');
  await expect(page.locator('[data-toggle-pane=left]')).not.toBeVisible();
  await expect(page.locator('[data-toggle-pane=right]')).not.toBeVisible();
  await splitter.press('Enter');
  await expect(page.locator('.workspace-left')).toBeVisible();
  await expect(page.locator('.workspace-right')).toBeVisible();
  await expect(page.getByLabel('Instructions', { exact: true })).toHaveValue('Keep the intention and tighten the wording.');
  await page.reload();
  await expect(splitter).toHaveAttribute('aria-valuenow', '210');
  await expect.poll(() => paper.evaluate(el => el.scrollTop)).toBeGreaterThan(scroll / 2);
  await page.locator('.workspace-layout-menu summary').click(); await page.getByRole('button', { name: 'Reset layout', exact: true }).click();
  await expect(splitter).toHaveAttribute('aria-valuenow', '200');
  await expect(page.getByRole('region', { name: 'Script assistant', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/workspace-script-desktop.png' });
});

test('mobile drawers trap focus and return after an assistant dialog without losing instructions', async ({ page, request }) => {
  const project = await (await request.get('/fixtures/new')).json();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`/projects/${project.id}/script`);
  await expect(page.locator('.studio-workspace')).toHaveAttribute('data-ready', 'true');
  await page.locator('[data-toggle-pane=right]').click();
  const drawer = page.getByRole('dialog', { name: 'Assistant', exact: true });
  await expect(drawer).toBeVisible();
  await expect(drawer.getByRole('button', { name: 'Close Assistant', exact: true })).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  expect(await drawer.evaluate(el => el.contains(document.activeElement))).toBeTruthy();
  await page.getByLabel('Instructions', { exact: true }).fill('Keep it short.');
  await drawer.getByRole('button', { name: 'Draft script', exact: true }).click();
  const proposal = page.locator('.script-review-dialog');
  await expect(proposal).toBeVisible();
  await expect(drawer).not.toBeVisible();
  await proposal.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(drawer).toBeVisible();
  await expect(page.getByLabel('Instructions', { exact: true })).toHaveValue('Keep it short.');
  await page.keyboard.press('Escape');
  await expect(drawer).not.toBeVisible();
  await expect(page.locator('[data-toggle-pane=right]')).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/workspace-script-mobile.png' });
});

test('reference and voice drafts apply together, cancel crops, and reject concurrent changes', async ({ page, request }) => {
  const { id } = await (await request.get('/fixtures/new')).json();
  const library = await (await request.post(`/fixtures/${id}/images`)).json();
  await request.post(`/fixtures/${id}/approved`);
  expect((await request.post(`/fixtures/${id}/reference-workspace`)).ok()).toBe(true);
  const assets = (await (await request.get(`/fixtures/${id}`)).json()).assets;
  await page.setViewportSize({ width: 1440, height: 850 });
  await page.goto(`/projects/${id}/shots`);
  await toolsTab(page, 'References');
  const state = async () => (await (await request.get(`/fixtures/${id}/production`)).json()).compositions[0].inputs;
  const details = page.locator('.manual-reference-dialog');
  await page.getByRole('button', { name: 'Manage references', exact: true }).click();
  await details.locator(`[data-reference="${library.assets[0].id}/${library.assets[0].images[0].id}"]`).click();
  await details.getByLabel('Voice for Juniper', { exact: true }).selectOption('none');
  await details.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect.poll(async () => (await state()).images.length).toBe(1);
  const original = (await state()).images[0];
  await editShotReference(page);
  await details.getByLabel('AI use hint', { exact: true }).selectOption('Framing');
  await cropReference(page, details);
  await details.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect((await state()).images[0]).toEqual(original);
  await expect(page.getByRole('button', { name: 'Manage references', exact: true })).toBeFocused();
  await editShotReference(page);
  await details.getByLabel('AI use hint', { exact: true }).selectOption('First frame');
  await details.getByRole('button', { name: 'Customize for this setup' }).click();
  await details.getByLabel('Composition preservation override').fill('Keep the hand position.');
  await cropReference(page, details);
  await expect(details.locator('.reference-crop-button').first()).toHaveClass(/is-active/);
  await details.getByLabel('Voice for Juniper', { exact: true }).selectOption(`voice:${assets.voices[0].id}`);
  await details.getByLabel('Speaker for Juniper', { exact: true }).selectOption('JUNIPER');
  await details.getByLabel('Audio start for Juniper').fill('7');
  await details.getByLabel('Audio start for Juniper').blur();
  await details.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(details.getByRole('alert')).toContainText(/within|exceed|recording/i);
  await details.getByLabel('Audio start for Juniper').fill('2');
  await details.getByLabel('Audio duration for Juniper').fill('4');
  await details.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(details).toBeHidden();
  await expect.poll(async () => (await state()).images[0].crop?.width).toBe(.5);
  expect((await state()).images[0].preservationOverride).toBe('Keep the hand position.');
  expect((await state()).characterVoices[0].recording.start).toBe(2);
  await editShotReference(page);
  await details.getByLabel('AI use hint', { exact: true }).selectOption('Framing');
  const other = await page.context().newPage();
  await other.goto(`/projects/${id}/shots`); await toolsTab(other, 'References'); await editShotReference(other);
  await other.locator('.manual-reference-dialog').getByLabel('AI use hint', { exact: true }).selectOption('Prop');
  await other.locator('.manual-reference-dialog').getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect.poll(async () => (await state()).images[0].aiUseHint).toBe('Prop');
  await other.close();
  await details.getByRole('button', { name: 'Apply changes', exact: true }).click();
  await expect(details.getByRole('alert')).toContainText('Another tab saved newer changes');
  await expect(details.getByLabel('AI use hint', { exact: true })).toHaveValue('Framing');
  expect((await state()).images[0].aiUseHint).toBe('Prop');
  await details.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.reload();
  await page.setViewportSize({ width: 390, height: 650 }); await toolsTab(page, 'References');
  await editShotReference(page);
  await expect(page.locator('.workspace-right')).toBeHidden();
  await details.getByLabel('AI use hint', { exact: true }).selectOption('Setting');
  await page.keyboard.press('Escape');
  await expect(page.locator('.workspace-right')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Manage references', exact: true })).toBeFocused();
  await expect(page.getByRole('button', { name: 'Generate takes', exact: true })).toBeInViewport();
  await page.screenshot({ path: 'test-results/workspace-shots-mobile.png' });
});

test('asset tools preserve author input, repair hidden settings, and keep actions visible in short windows', async ({ page, request }) => {
  const project = await (await request.get('/fixtures/new')).json();
  await request.post(`/fixtures/${project.id}/images`);
  await page.setViewportSize({ width: 1440, height: 650 });
  await page.goto(`/projects/${project.id}/assets`);
  await toolsTab(page, 'Prompt');
  await page.getByLabel('Image prompt', { exact: true }).fill('A quiet portrait in soft light.');
  await imageOutput(page);
  await page.locator('.image-generation-settings > summary').click();
  await page.locator('#fixed-seed').fill('invalid');
  await page.locator('.image-generation-settings > summary').click();
  await toolsTab(page, 'Inputs');
  await page.getByRole('button', { name: 'Generate images', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Edit seed', exact: true })).toBeInViewport();
  await page.getByRole('button', { name: 'Edit seed', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Create image', exact: true })).toBeVisible();
  await expect(page.locator('#fixed-seed')).toBeFocused();
  await page.locator('#fixed-seed').fill('42');
  await toolsTab(page, 'Prompt');
  await expect(page.getByLabel('Image prompt', { exact: true })).toHaveValue('A quiet portrait in soft light.');
  const right = page.getByRole('separator', { name: 'Asset tools', exact: true });
  const originalWidth = Number(await right.getAttribute('aria-valuenow'));
  await right.focus(); await page.keyboard.press('ArrowLeft');
  await expect(right).toHaveAttribute('aria-valuenow', String(originalWidth + 10));
  await right.press('Enter');
  await expect(page.locator('.workspace-right')).toBeVisible();
  await expect(page.getByLabel('Image prompt', { exact: true })).toHaveValue('A quiet portrait in soft light.');
  expect(await page.evaluate(() => scrollY)).toBe(0);
  await expect(page.getByRole('button', { name: 'Generate images', exact: true })).toBeInViewport();
  await page.screenshot({ path: 'test-results/workspace-assets-short.png' });
  await page.setViewportSize({ width: 900, height: 700 });
  await expect(page.locator('.workspace-left')).toBeVisible();
  await expect(page.locator('.workspace-right')).not.toBeVisible();
  await toolsTab(page, 'Prompt');
  await expect(page.getByLabel('Image prompt', { exact: true })).toHaveValue('A quiet portrait in soft light.');
  await page.keyboard.press('Escape');
  await expect(page.locator('[data-toggle-pane=right]')).toBeFocused();
  await page.setViewportSize({ width: 390, height: 550 });
  await toolsTab(page, 'Prompt');
  await expect(page.getByRole('button', { name: 'Generate images', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/workspace-assets-mobile-short.png' });
});
